export const RARE_IMAGES: Record<string, any> = {
    nanami_kento: require('./nanami_kento.png'),
    leorio: require('./leorio.png'),
    grimmjow_jaegerjaquez: require('./grimmjow_jaegerjaquez.png'),
    rock_lee: require('./rock_lee.png'),
    nami: require('./nami.png'),
    barry_the_chopper: require('./barry_the_chopper.png'),
        dende: require('./dende.png'),
    dr_cossack: require('./dr_cossack.png'),
    emlyn_white: require('./emlyn_white.png'),
    falco_grice: require('./falco_grice.png'),
    franky: require('./franky.png'),
    gon_freecss: require('./Gon_Freecss.png'),
            rundelhaus: require('./rundelhaus.jpg'),
        sasha_braus: require('./sasha_braus.png'),
    silica: require('./silica.png'),
    subaru_natsuki: require('./Subaru_Natsuki.jpg'),
    suspicious_beggar: require('./suspicious_beggar.png'),
    tien_shinhan: require('./tien_shinhan.png'),
    tony_tony_chopper: require('./tony_tony_chopper.png'),
    usopp: require('./usopp.png'),
    yamcha: require('./yamcha.png'),
    floki: require('./floki.png'),
};
