export const LEGENDARY_IMAGES: Record<string, any> = {
    reiner_braun: require('./reiner_braun.png'),
    trunks: require('./trunks.png'),
    acnologia: require('./Acnologia.png'),
    alduin: require('./Alduin.png'),
    alucard: require('./Alucard.png'),
    artorias: require('./Artorias.png'),
    cell: require('./cell.png'),
    death: require('./Death.png'),
    diablo: require('./Diablo.png'),
    dracula: require('./Dracula.png'),
    fatalis: require('./Fatalis.png'),
    ganondorf: require('./Ganondorf.png'),
    garou: require('./Garou.png'),
    gaunter_o_dimm: require('./gaunter_o_dimm.png'),
    giyu_tomioka: require('./giyu_tomioka.png'),
    griffith: require('./Griffith.png'),
    gwyn: require('./Gwyn.png'),
    hisoka_morow: require('./Hisoka_Morow.png'),
    igneel: require('./Igneel.png'),
    kaguya_otsutsuki: require('./kaguya_otsutsuki.png'),
    ken_kaneki: require('./Ken_Kaneki.png'),
    klein_moretti: require('./Klein_Moretti.png'),
    kishou_arima: require('./kishou_arima.png'),
    kyojuro_rengoku: require('./Kyojuro_Rengoku.png'),
    lady_maria: require('./Lady_Maria.png'),
    levi_ackerman: require('./levi_ackerman.png'),
    lilith: require('./lilith.png'),
    makima: require('./Makima.png'),
    meruem: require('./meruem.png'),
    muichiro_tokito: require('./Muichiro_Tokito.png'),
    muzan_kibutsuji: require('./Muzan_Kibutsuji.png'),
    paarthurnax: require('./paarthurnax.png'),
    saitama: require('./Saitama.png'),
    satella: require('./Satella.png'),
    son_goku: require('./Son_Goku.png'),
    the_hunter: require('./the_hunter.png'),
    ulquiorra_cifer: require('./Ulquiorra_Cifer.png'),
};

/** فيديوهات الكروت الأسطورية — mp4 */
export const LEGENDARY_VIDEOS: Record<string, any> = {
    akaza: require('./akaza.mp4'),
    all_might: require('./all_might.mp4'),
    broly: require('./broly.mp4'),
    byakuya_kuchiki: require('./byakuya_kuchiki.mp4'),
    chrollo_lucilfer: require('./chrollo_lucilfer.mp4'),
    doma: require('./doma.mp4'),
    dracule_mihawk: require('./Dracule_Mihawk.mp4'),
    eren_yeager: require('./eren_yeager.mp4'),
    feanor: require('./Feanor.mp4'),
    gehrman: require('./gehrman.mp4'),
    gol_d_roger: require('./Gol_D_Roger.mp4'),
    guts: require('./Guts.mp4'),
    ichigo_kurosaki: require('./ichigo_kurosaki.mp4'),
    itachi_uchiha: require('./itachi_uchiha.mp4'),
    kaido: require('./kaido.mp4'),
    kenpachi_zaraki: require('./Kenpachi_Zaraki.mp4'),
    kenpachi_zaraki_rage: require('./kenpachi_zaraki_rage.mp4'),
    kokushibo: require('./Kokushibo.mp4'),
    laurence: require('./laurence.mp4'),
    ludwig: require('./Ludwig.mp4'),
    madara_uchiha: require('./madara_uchiha.mp4'),
    minato_namikaze: require('./minato_namikaze.mp4'),
    monkey_d_luffy: require('./monkey_d_luffy.mp4'),
    naruto_uzumaki: require('./naruto_uzumaki.mp4'),
    obito_uchiha: require('./obito_uchiha.mp4'),
    pain_nagato: require('./pain_nagato.mp4'),
    roronoa_zoro: require('./Roronoa_Zoro.mp4'),
    ryomen_sukuna: require('./ryomen_sukuna.mp4'),
    satoru_gojo: require('./satoru_gojo.mp4'),
    sosuke_aizen: require('./sosuke_aizen.mp4'),
    white_snake: require('./white_snake.mp4'),
};

/** ملفات GIF */
export const LEGENDARY_GIFS: Record<string, any> = {
    isaac_netero: require('./Isaac_Netero.gif'),
    sasuke_uchiha: require('./sasuke_uchiha.gif'),
};
