/**
 * ability-details.ts
 * ─────────────────
 * Structured ability data for the UI — every ability has:
 *   - trigger: when it activates
 *   - effect:  what stat / game state it changes
 *   - duration: how long it lasts
 *   - category: buff / debuff / utility / special
 *   - targetSide: who it affects
 *   - condition/cooldown: any limits
 */
import { AbilityType } from './types';

export type AbilityCategory = 'buff' | 'debuff' | 'utility' | 'special';
export type AbilityTarget = 'self' | 'opponent' | 'both';

export interface AbilityDetail {
  nameAr: string;
  nameEn: string;
  triggerAr: string;
  triggerEn: string;
  effectAr: string;
  effectEn: string;
  durationAr: string;
  durationEn: string;
  category: AbilityCategory;
  targetSide: AbilityTarget;
  conditionAr?: string;
  conditionEn?: string;
  cooldownAr?: string;
  cooldownEn?: string;
}

// ─── Trigger Emojis ─────────────────────────────────────────────────────
export const TRIGGER_EMOJI: Record<string, string> = {
  instant: '⚡',
  onWin: '🏆',
  onLoss: '💀',
  beforeRound: '⏳',
  afterRound: '🔄',
  passive: '🔮',
  conditional: '⚙️',
};

export const CATEGORY_CONFIG: Record<AbilityCategory, { emoji: string; color: string; labelAr: string }> = {
  buff:    { emoji: '⬆️', color: '#4ade80', labelAr: 'تعزيز' },
  debuff:  { emoji: '⬇️', color: '#f87171', labelAr: 'إضعاف' },
  utility: { emoji: '🔧', color: '#60a5fa', labelAr: 'أداة' },
  special: { emoji: '✨', color: '#e879f9', labelAr: 'خاص' },
};

// ─── All Ability Details ────────────────────────────────────────────────
export const ABILITY_DETAILS: Record<AbilityType, AbilityDetail> = {
  LogicalEncounter: {
    nameAr: 'مصادفة منطقية',
    nameEn: 'Logical Encounter',
    triggerAr: 'فوري — يتم التحقق بعد كل جولة',
    triggerEn: 'Instant — verified after each round',
    effectAr: 'توقّع نتيجة جولتين قادمتين (فوز/خسارة). التوقع الصحيح = الخصم يخسر 1 HP إضافي. التوقع الخاطئ = أنت تخسر 1 HP',
    effectEn: 'Predict outcome of next 2 rounds. Correct = opponent loses 1 extra HP. Wrong = you lose 1 HP',
    durationAr: 'جولتين قادمتين',
    durationEn: '2 upcoming rounds',
    category: 'utility',
    targetSide: 'self',
  },
  Recall: {
    nameAr: 'استدعاء',
    nameEn: 'Recall',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'استبدل كرتك الحالي بكرت سابق لك (بدون خاصيته)',
    effectEn: 'Replace your current card with a past card (without its ability)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'self',
    conditionAr: 'يتطلب وجود كرت سابق على الأقل',
    conditionEn: 'Requires at least 1 past round',
  },
  Protection: {
    nameAr: 'حماية',
    nameEn: 'Protection',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تمنع خسارة 1 HP هذه الجولة حتى لو خسرت',
    effectEn: 'Prevents 1 HP loss this round even if you lose',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
  },
  Arise: {
    nameAr: 'أرايز',
    nameEn: 'Arise',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'استدعِ كرتاً من كروت خصمك السابقة ليكون كرتك (بدون خاصيته)',
    effectEn: 'Summon an opponent\'s past card as yours (without ability)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'self',
    conditionAr: 'يتطلب وجود كرت سابق للخصم',
    conditionEn: 'Requires at least 1 past opponent round',
  },
  Reinforcement: {
    nameAr: 'التدعيم',
    nameEn: 'Reinforcement',
    triggerAr: 'عند الفوز',
    triggerEn: 'On Win',
    effectAr: '+1 دفاع لجميع كروتك المتبقية',
    effectEn: '+1 DEF to all your remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتفعّل فقط إذا فزت بهذه الجولة',
    conditionEn: 'Activates only if you win this round',
  },
  Wipe: {
    nameAr: 'المسح',
    nameEn: 'Wipe',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'إزالة جميع التأثيرات (بفات ونيرفات) المؤثرة عليك',
    effectEn: 'Remove ALL effects (buffs & debuffs) targeting you',
    durationAr: 'فوري — لا يبقى تأثير',
    durationEn: 'Instant — no lingering effect',
    category: 'utility',
    targetSide: 'self',
  },
  Purge: {
    nameAr: 'التطهير',
    nameEn: 'Purge',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'إزالة جميع التأثيرات من اللعبة (لك وللخصم معاً)',
    effectEn: 'Remove ALL effects from the entire game (yours and opponent)',
    durationAr: 'فوري — إعادة ضبط كل شيء',
    durationEn: 'Instant — full reset',
    category: 'utility',
    targetSide: 'both',
  },
  HalvePoints: {
    nameAr: 'تنصيف النقاط',
    nameEn: 'Halve Points',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تنصيف خسارة HP للخصم هذه الجولة (إذا خسر يخسر نصف المعتاد)',
    effectEn: 'Halve the opponent\'s HP loss this round',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Seal: {
    nameAr: 'الختم',
    nameEn: 'Seal',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'يمنع الخصم من استخدام أي قدرة لمدة 5 جولات',
    effectEn: 'Prevents opponent from using any ability for 5 rounds',
    durationAr: '5 جولات',
    durationEn: '5 rounds',
    category: 'debuff',
    targetSide: 'opponent',
  },
  DoubleOrNothing: {
    nameAr: 'دبل أو نثنق',
    nameEn: 'Double Or Nothing',
    triggerAr: 'قبل الراوند',
    triggerEn: 'Before Round',
    effectAr: 'إذا فزت: الخصم يخسر 2 HP. إذا خسرت: أنت تخسر 2 HP',
    effectEn: 'Win: opponent loses 2 HP. Lose: you lose 2 HP',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'special',
    targetSide: 'both',
    conditionAr: '⚠️ خطير — قد يرتد عليك',
    conditionEn: '⚠️ Risky — can backfire',
  },
  StarSuperiority: {
    nameAr: 'تفوق النجوم',
    nameEn: 'Star Superiority',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تفوز بالجولة بأفضلية النجوم بغض النظر عن الإحصائيات',
    effectEn: 'Force win this round via star advantage regardless of stats',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
  },
  Reduction: {
    nameAr: 'التقليص',
    nameEn: 'Reduction',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: '-2 هجوم للخصم هذه الجولة',
    effectEn: '-2 ATK to opponent this round',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Sacrifice: {
    nameAr: 'تضحية',
    nameEn: 'Sacrifice',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'إذا خسرت: يُزال أقوى تأثير إيجابي من الخصم',
    effectEn: 'On loss: removes opponent\'s strongest positive effect',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  Popularity: {
    nameAr: 'الشعبية',
    nameEn: 'Popularity',
    triggerAr: 'فوري — يتفعّل في الجولة المختارة',
    triggerEn: 'Instant — activates in chosen round',
    effectAr: 'اختر جولة مستقبلية: ستفوز بها تلقائياً (نتيجة مضمونة)',
    effectEn: 'Choose a future round: you auto-win it (forced outcome)',
    durationAr: 'جولة مستقبلية واحدة',
    durationEn: 'One future round',
    category: 'special',
    targetSide: 'self',
  },
  Eclipse: {
    nameAr: 'الخسوف',
    nameEn: 'Eclipse',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'هجوم الخصم = 0 هذه الجولة (قبل البفات)',
    effectEn: 'Opponent ATK = 0 this round (before buffs)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  CancelAbility: {
    nameAr: 'إلغاء الخاصية',
    nameEn: 'Cancel Ability',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'إلغاء جميع تأثيرات الخصم + منعه من استخدام القدرات هذه الجولة',
    effectEn: 'Cancel all opponent effects + silence abilities this round',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Revive: {
    nameAr: 'إنعاش',
    nameEn: 'Revive',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'استبدل كرتك بكرت سابق لك بنصف الهجوم والدفاع (مع خاصيته)',
    effectEn: 'Replace your card with a past card at 50% ATK/DEF (keeps ability)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'self',
    conditionAr: 'يتطلب وجود كرت سابق',
    conditionEn: 'Requires at least 1 past round',
  },
  ConsecutiveLossBuff: {
    nameAr: 'تعزيز الخسارة',
    nameEn: 'Consecutive Loss Buff',
    triggerAr: 'بعد خسارتين متتاليتين',
    triggerEn: 'After 2 consecutive losses',
    effectAr: 'بعد خسارة جولتين متتاليتين: +1 هجوم و +1 دفاع لجميع كروتك',
    effectEn: 'After 2 consecutive losses: +1 ATK and +1 DEF to all your cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتطلب خسارة جولتين متتاليتين للتفعيل',
    conditionEn: 'Requires 2 consecutive losses to activate',
  },
  Lifesteal: {
    nameAr: 'سرقة الحياة',
    nameEn: 'Lifesteal',
    triggerAr: 'عند الفوز',
    triggerEn: 'On Win',
    effectAr: 'عند الفوز: الخصم يخسر 1 HP إضافي (المجموع 2 HP)',
    effectEn: 'On win: opponent loses 1 extra HP (total 2 HP)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتفعّل فقط عند الفوز',
    conditionEn: 'Only triggers on win',
  },
  Revenge: {
    nameAr: 'الانتقام',
    nameEn: 'Revenge',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'عند الخسارة: +1 هجوم لجميع كروتك المتبقية',
    effectEn: 'On loss: +1 ATK to all remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  Suicide: {
    nameAr: 'الانتحار',
    nameEn: 'Suicide',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'عند الخسارة: الخصم يخسر أيضاً 1 HP (لا يربح HP من هذه الجولة)',
    effectEn: 'On loss: opponent also loses 1 HP (no HP gain from this round)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'special',
    targetSide: 'opponent',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  Disaster: {
    nameAr: 'النكبة',
    nameEn: 'Disaster',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'استبدل كرت الخصم الحالي بكرت سابق له (تختار أي كرت)',
    effectEn: 'Replace opponent\'s current card with one of their past cards (you choose)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
    conditionAr: 'يتطلب وجود كرت سابق للخصم',
    conditionEn: 'Requires opponent past cards',
  },
  Compensation: {
    nameAr: 'التعويض',
    nameEn: 'Compensation',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'عند الخسارة: +1 دفاع لجميع كروتك المتبقية',
    effectEn: 'On loss: +1 DEF to all remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  Weakening: {
    nameAr: 'الإضعاف',
    nameEn: 'Weakening',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'عند الخسارة: -1 هجوم لجميع كروت الخصم المتبقية',
    effectEn: 'On loss: -1 ATK to all opponent remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'debuff',
    targetSide: 'opponent',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  Misdirection: {
    nameAr: 'التضليل',
    nameEn: 'Misdirection',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'مضاعفة جميع النيرفات (التأثيرات السلبية) على الخصم',
    effectEn: 'Double all debuffs currently on opponent',
    durationAr: 'فوري — التعديل دائم',
    durationEn: 'Instant — modification is permanent',
    category: 'debuff',
    targetSide: 'opponent',
  },
  StealAbility: {
    nameAr: 'سرقة الخاصية',
    nameEn: 'Steal Ability',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'اسرق قدرة عشوائية غير مستخدمة من الخصم (تصبح لك)',
    effectEn: 'Steal a random unused ability from opponent (becomes yours)',
    durationAr: 'فوري — القدرة المسروقة تبقى معك',
    durationEn: 'Instant — stolen ability stays with you',
    category: 'utility',
    targetSide: 'opponent',
  },
  Rescue: {
    nameAr: 'الإنقاذ',
    nameEn: 'Rescue',
    triggerAr: 'فوري — يتفعّل الجولة القادمة',
    triggerEn: 'Instant — activates next round',
    effectAr: 'دفاع كرتك الحالي يُضاف لكرتك القادم (لا يُستبدل)',
    effectEn: 'Current card\'s DEF is added to next card (not replaced)',
    durationAr: 'الجولة القادمة فقط',
    durationEn: 'Next round only',
    category: 'buff',
    targetSide: 'self',
  },
  Trap: {
    nameAr: 'الفخ',
    nameEn: 'Trap',
    triggerAr: 'قبل الراوند',
    triggerEn: 'Before Round',
    effectAr: 'الخصم يخسر هذه الجولة تلقائياً — أنت تفوز بـ HP',
    effectEn: 'Opponent auto-loses this round — you gain HP advantage',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'special',
    targetSide: 'opponent',
  },
  ConvertDebuffsToBuffs: {
    nameAr: 'تحويل السلبيات',
    nameEn: 'Convert Debuffs',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تحويل جميع النيرفات عليك إلى بفات (القيم السالبة تصبح موجبة)',
    effectEn: 'Convert all your debuffs to buffs (negative values become positive)',
    durationAr: 'فوري — التحويل دائم',
    durationEn: 'Instant — conversion is permanent',
    category: 'buff',
    targetSide: 'self',
  },
  Sniping: {
    nameAr: 'القنص',
    nameEn: 'Sniping',
    triggerAr: 'فوري — يتفعّل في الجولة المختارة',
    triggerEn: 'Instant — activates in chosen round',
    effectAr: 'اختر جولة مستقبلية: ستفوز بها تلقائياً (نتيجة مضمونة)',
    effectEn: 'Choose a future round: you auto-win it (forced outcome)',
    durationAr: 'جولة مستقبلية واحدة',
    durationEn: 'One future round',
    category: 'special',
    targetSide: 'self',
  },
  Merge: {
    nameAr: 'الدمج',
    nameEn: 'Merge',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'ادمج كرتك الحالي مع كرت سابق: هجوم + دفاع الكرت السابق يُضافان لكرتك',
    effectEn: 'Merge current card with past card: past card ATK+DEF added to yours',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتطلب وجود كرت سابق',
    conditionEn: 'Requires at least 1 past round',
  },
  DoubleNextCards: {
    nameAr: 'المضاعفة',
    nameEn: 'Double Next Cards',
    triggerAr: 'فوري — يتفعّل الجولتين القادمتين',
    triggerEn: 'Instant — activates next 2 rounds',
    effectAr: 'مضاعفة هجوم كرتيك القادمتين (الهجوم × 2)',
    effectEn: 'Double ATK of your next 2 cards (ATK × 2)',
    durationAr: 'الجولتين القادمتين',
    durationEn: 'Next 2 rounds',
    category: 'buff',
    targetSide: 'self',
  },
  Deprivation: {
    nameAr: 'السلب',
    nameEn: 'Deprivation',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'سلب أقوى بف من الخصم وإضافته لك',
    effectEn: 'Steal opponent\'s strongest buff and add it to yourself',
    durationAr: 'فوري — البف المسلوب يبقى معك',
    durationEn: 'Instant — stolen buff stays with you',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Greed: {
    nameAr: 'الجشع',
    nameEn: 'Greed',
    triggerAr: 'عند الفوز',
    triggerEn: 'On Win',
    effectAr: 'عند الفوز: +1 هجوم لجميع كروتك المتبقية',
    effectEn: 'On win: +1 ATK to all remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'يتفعّل فقط عند الفوز',
    conditionEn: 'Only triggers on win',
  },
  Dilemma: {
    nameAr: 'الوهقة',
    nameEn: 'Dilemma',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'استبدل كرت الخصم الحالي بكرت سابق لك (تختاره أنت)',
    effectEn: 'Replace opponent\'s current card with one of your past cards (you choose)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
    conditionAr: 'يتطلب وجود كرت سابق لك',
    conditionEn: 'Requires at least 1 of your past rounds',
  },
  Subhan: {
    nameAr: 'الصبحان',
    nameEn: 'Subhan',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'خمّن هجوم كرت الخصم. إذا كان التخمين ضمن ±3: +2 هجوم لك هذه الجولة',
    effectEn: 'Guess opponent ATK. If within ±3: +2 ATK for you this round',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
    conditionAr: 'هامش خطأ ±3 مقبول',
    conditionEn: 'Error margin ±3 accepted',
  },
  Propaganda: {
    nameAr: 'بروباغاندا',
    nameEn: 'Propaganda',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'اختر فئة كرت: جميع كروت الخصم من هذه الفئة تخسر -2 هجوم و -2 دفاع',
    effectEn: 'Choose a card class: all opponent cards of that class get -2 ATK & -2 DEF',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'debuff',
    targetSide: 'opponent',
  },
  DoubleYourBuffs: {
    nameAr: 'مضاعفة البفات',
    nameEn: 'Double Your Buffs',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'مضاعفة قيمة جميع البفات الإيجابية لديك (×2)',
    effectEn: 'Double the value of all your positive buffs (×2)',
    durationAr: 'فوري — التعديل دائم',
    durationEn: 'Instant — modification is permanent',
    category: 'buff',
    targetSide: 'self',
  },
  Avatar: {
    nameAr: 'أفاتار',
    nameEn: 'Avatar',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: '+2 هجوم و +2 دفاع لجميع كروتك المتبقية',
    effectEn: '+2 ATK and +2 DEF to all remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'buff',
    targetSide: 'self',
  },
  Penetration: {
    nameAr: 'الاختراق',
    nameEn: 'Penetration',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'دفاع الخصم = 0 هذه الجولة (يتجاهل كل الدفاع)',
    effectEn: 'Opponent DEF = 0 this round (ignores all defense)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Pool: {
    nameAr: 'المسبح',
    nameEn: 'Pool',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'يُلغى تأثير كرت الخصم — لا يخسر HP حتى لو فاز',
    effectEn: 'Nullifies opponent\'s card impact — no HP gain even if they win',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Conversion: {
    nameAr: 'التحويل',
    nameEn: 'Conversion',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تحويل جميع بفات الخصم إلى نيرفات (القيم الموجبة تصبح سالبة)',
    effectEn: 'Convert all opponent buffs to debuffs (positive values become negative)',
    durationAr: 'فوري — التحويل دائم',
    durationEn: 'Instant — conversion is permanent',
    category: 'debuff',
    targetSide: 'opponent',
  },
  Shield: {
    nameAr: 'الدرع',
    nameEn: 'Shield',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'حماية من خسارة HP + حجب التأثيرات السلبية هذه الجولة. إذا خسرت تتحول لتعادل',
    effectEn: 'Prevents HP loss + blocks debuffs this round. Loss becomes draw',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
  },
  SwapClass: {
    nameAr: 'تبديل الفئة',
    nameEn: 'Swap Class',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تبديل فئة كرتك مع فئة كرت الخصم (يؤثر على بروباغاندا)',
    effectEn: 'Swap your card\'s class with opponent\'s card class (affects Propaganda)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'both',
  },
  TakeIt: {
    nameAr: 'خذها وأنا بو مبارك',
    nameEn: 'Take It',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'نقل جميع النيرفات (التأثيرات السلبية) من عندك إلى الخصم',
    effectEn: 'Transfer all your debuffs (negative effects) to the opponent',
    durationAr: 'فوري — النيرفات تنتقل دائماً',
    durationEn: 'Instant — debuffs transferred permanently',
    category: 'utility',
    targetSide: 'opponent',
  },
  Skip: {
    nameAr: 'تخطي',
    nameEn: 'Skip',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'يصبح هذا الراوند تعادل — لا أحد يخسر HP',
    effectEn: 'This round becomes a draw — nobody loses HP',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'both',
  },
  AddElement: {
    nameAr: 'تغيير الفصيلة',
    nameEn: 'Change Faction',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'تغيير فصيلة كرتك الحالي لفصيلة تختارها (يؤثر على أفضلية الفصائل)',
    effectEn: 'Change your current card faction (affects faction advantage)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'utility',
    targetSide: 'self',
  },
  Explosion: {
    nameAr: 'الانفجار',
    nameEn: 'Explosion',
    triggerAr: 'عند الخسارة',
    triggerEn: 'On Loss',
    effectAr: 'عند الخسارة: -1 دفاع لجميع كروت الخصم المتبقية',
    effectEn: 'On loss: -1 DEF to all opponent remaining cards',
    durationAr: 'دائم (حتى نهاية المباراة)',
    durationEn: 'Permanent (until match end)',
    category: 'debuff',
    targetSide: 'opponent',
    conditionAr: 'يتفعّل فقط عند الخسارة',
    conditionEn: 'Only triggers on loss',
  },
  DoublePoints: {
    nameAr: 'مضاعفة النقاط',
    nameEn: 'Double Points',
    triggerAr: 'قبل الراوند',
    triggerEn: 'Before Round',
    effectAr: 'مضاعفة نقاط HP المتبادلة: الفائز يأخذ 2 HP بدل 1',
    effectEn: 'Double HP swing: winner takes 2 HP instead of 1',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'special',
    targetSide: 'both',
    conditionAr: '⚠️ ينطبق على الفائز بغض النظر عن الطرف',
    conditionEn: '⚠️ Applies to winner regardless of side',
  },
  ElementalMastery: {
    nameAr: 'إتقان الفصائل',
    nameEn: 'Faction Mastery',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'أفضلية فصيلية كاملة هذه الجولة (×1.25)',
    effectEn: 'Full faction advantage this round (×1.25)',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
  },
  LoseHalfRounds: {
    nameAr: 'تخسر نصف الجولات',
    nameEn: 'Lose Half Rounds',
    triggerAr: 'تلقائي — طوال النصف الأول',
    triggerEn: 'Automatic — throughout first half',
    effectAr: 'تخسر النصف الأول من الجولات إجبارياً (مثال: 10 جولات ← تخسر 1 إلى 5)',
    effectEn: 'Auto-lose the first half of rounds (e.g., 10 rounds → lose rounds 1-5)',
    durationAr: 'النصف الأول من المباراة',
    durationEn: 'First half of the match',
    category: 'debuff',
    targetSide: 'self',
    conditionAr: '⚠️ عقوبة تورين — لا يمكن إلغاؤها',
    conditionEn: '⚠️ Turin penalty — cannot be cancelled',
  },
  AbsoluteDominance: {
    nameAr: 'السيطرة المطلقة',
    nameEn: 'Absolute Dominance',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'فوز مضمون بأعلى أولوية — يتجاوز كل القدرات وأفضليات الفصائل والنتائج المضمونة',
    effectEn: 'Guaranteed win with highest priority — overrides all abilities, faction advantages, and forced outcomes',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'special',
    targetSide: 'self',
    cooldownAr: 'مرة واحدة فقط في المباراة',
    cooldownEn: 'Once per match only',
  },
  InfinityLoop: {
    nameAr: 'الحلقة الأبدية',
    nameEn: 'Infinity Loop',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'إعادة آخر 3 جولات — يُعاد حساب النقاط كأن الجولات لم تحدث',
    effectEn: 'Rewind last 3 rounds — scores recalculated as if those rounds never happened',
    durationAr: 'فوري — يُعاد لعب الجولات',
    durationEn: 'Instant — rounds replayed',
    category: 'special',
    targetSide: 'both',
    cooldownAr: 'مرة واحدة فقط في المباراة',
    cooldownEn: 'Once per match only',
    conditionAr: 'يتطلب وجود 1-3 جولات سابقة',
    conditionEn: 'Requires 1-3 past rounds',
  },
  PhantomBlade: {
    nameAr: 'شفرة الوهم',
    nameEn: 'Phantom Blade',
    triggerAr: 'فوري',
    triggerEn: 'Instant',
    effectAr: 'هجوم كرتك يُضاعف (×2) هذه الجولة',
    effectEn: 'Your card\'s ATK is doubled (×2) this round',
    durationAr: 'هذه الجولة فقط',
    durationEn: 'This round only',
    category: 'buff',
    targetSide: 'self',
    cooldownAr: 'مرة واحدة فقط في المباراة',
    cooldownEn: 'Once per match only',
  },
};

/**
 * Get full structured detail for an ability
 */
export function getAbilityDetail(abilityType: AbilityType): AbilityDetail | undefined {
  return ABILITY_DETAILS[abilityType];
}

/**
 * Build a single-line summary for toast/modal display
 * e.g. "⚡ فوري · +2 هجوم و +2 دفاع · ⏱ دائم"
 */
export function getAbilitySummaryLine(abilityType: AbilityType): string {
  const d = ABILITY_DETAILS[abilityType];
  if (!d) return '';
  const cat = CATEGORY_CONFIG[d.category];
  return `${cat.emoji} ${d.triggerAr} · ${d.effectAr}`;
}
