import { Card } from './types';

// Batch 8/8 — 49 cards (orphaned-media recovery: epic second half + legendary)
export const CARDS_BATCH_8: Card[] = [
    // ═══════════════════════════════════════════════════════════════════════
    // EPIC — second half (stars 4)
    // ═══════════════════════════════════════════════════════════════════════
    {
        id: 'petelgeuse',
        name: 'Petelgeuse Romanee-Conti',
        nameAr: 'بيتيلجيوس روماني-كونتي',
        attack: 15,
        defense: 14,
        race: 'undead',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Re:Zero',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'regis',
        name: 'Regis',
        nameAr: 'ريجيس',
        attack: 15,
        defense: 14,
        race: 'undead',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'The Witcher',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'rei_ayanami',
        name: 'Rei Ayanami',
        nameAr: 'ري أيانامي',
        attack: 14,
        defense: 15,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Evangelion',
        animationPreset: 'water',
        tags: [],
    },
    {
        id: 'rin_okumura',
        name: 'Rin Okumura',
        nameAr: 'رين أوكومورا',
        attack: 16,
        defense: 13,
        race: 'demon',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Blue Exorcist',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'roswaal',
        name: 'Roswaal L. Mathers',
        nameAr: 'روزوال ل. ماثرز',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Re:Zero',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'sabo',
        name: 'Sabo',
        nameAr: 'سابو',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'fighter',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'shoto_todoroki',
        name: 'Shoto Todoroki',
        nameAr: 'شوتو تودوروكي',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'sigma',
        name: 'Sigma',
        nameAr: 'سيغما',
        attack: 17,
        defense: 15,
        race: 'robot',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Mega Man',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'smough',
        name: 'Executioner Smough',
        nameAr: 'المنفذ سموغ',
        attack: 16,
        defense: 15,
        race: 'monster',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Dark Souls',
        animationPreset: 'lightning',
        tags: [],
    },
    {
        id: 'suguru_geto',
        name: 'Suguru Geto',
        nameAr: 'سوغورو غيتو',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'tengen_uzui',
        name: 'Tengen Uzui',
        nameAr: 'تينغن أوزوي',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Demon Slayer',
        animationPreset: 'wind',
        tags: [],
    },
    {
        id: 'thorfinn',
        name: 'Thorfinn',
        nameAr: 'ثورفين',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Vinland Saga',
        animationPreset: 'wind',
        tags: [],
    },
    {
        id: 'thorkell',
        name: 'Thorkell',
        nameAr: 'ثوركيل',
        attack: 17,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Vinland Saga',
        animationPreset: 'earth',
        tags: ['crown'],
    },
    {
        id: 'tomura_shigaraki',
        name: 'Tomura Shigaraki',
        nameAr: 'تومورا شيغاراكي',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'fighter',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'touka_kirishima',
        name: 'Touka Kirishima',
        nameAr: 'توكا كيريشيما',
        attack: 15,
        defense: 13,
        race: 'monster',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Tokyo Ghoul',
        animationPreset: 'wind',
        tags: [],
    },
    {
        id: 'zero',
        name: 'Zero',
        nameAr: 'زيرو',
        attack: 16,
        defense: 15,
        race: 'robot',
        cardClass: 'swordsman',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Mega Man',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'zodd',
        name: 'Nosferatu Zodd',
        nameAr: 'نوسفيراتو زود',
        attack: 17,
        defense: 15,
        race: 'demon',
        cardClass: 'berserker',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Berserk',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'enel',
        name: 'Enel',
        nameAr: 'إينيل',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'lightning',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'lightning',
        tags: [],
    },
    {
        id: 'amygdala',
        name: 'Amygdala',
        nameAr: 'أميغدالا',
        attack: 16,
        defense: 15,
        race: 'monster',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'unknown',
        universe: 'Bloodborne',
        animationPreset: 'default',
        tags: [],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // LEGENDARY (stars 5)
    // ═══════════════════════════════════════════════════════════════════════
    {
        id: 'acnologia',
        name: 'Acnologia',
        nameAr: 'أكنولوغيا',
        attack: 21,
        defense: 19,
        race: 'dragon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Fairy Tail',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'alduin',
        name: 'Alduin',
        nameAr: 'ألدوين',
        attack: 20,
        defense: 20,
        race: 'dragon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'The Elder Scrolls',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'all_might',
        name: 'All Might',
        nameAr: 'أول مايت',
        attack: 21,
        defense: 19,
        race: 'human',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'alucard',
        name: 'Alucard',
        nameAr: 'ألوكارد',
        attack: 20,
        defense: 18,
        race: 'undead',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Hellsing',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'artorias',
        name: 'Knight Artorias',
        nameAr: 'الفارس أرتورياس',
        attack: 19,
        defense: 19,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Dark Souls',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'chrollo_lucilfer',
        name: 'Chrollo Lucilfer',
        nameAr: 'كرولو لوسيلفر',
        attack: 18,
        defense: 17,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Hunter x Hunter',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'death',
        name: 'Death',
        nameAr: 'الموت',
        attack: 19,
        defense: 17,
        race: 'undead',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'unknown',
        universe: 'Castlevania',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'diablo',
        name: 'Diablo',
        nameAr: 'ديابلو',
        attack: 20,
        defense: 18,
        race: 'demon',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Diablo',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'dracula',
        name: 'Dracula',
        nameAr: 'دراكولا',
        attack: 21,
        defense: 20,
        race: 'undead',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Castlevania',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'fatalis',
        name: 'Fatalis',
        nameAr: 'فتاليس',
        attack: 20,
        defense: 20,
        race: 'dragon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'unknown',
        universe: 'Monster Hunter',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'feanor',
        name: 'Fëanor',
        nameAr: 'فيانور',
        attack: 19,
        defense: 18,
        race: 'elf',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Middle-earth',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'ganondorf',
        name: 'Ganondorf',
        nameAr: 'غانوندورف',
        attack: 20,
        defense: 19,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Zelda',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'garou',
        name: 'Garou',
        nameAr: 'غارو',
        attack: 20,
        defense: 18,
        race: 'human',
        cardClass: 'fighter',
        element: 'earth',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'One Punch Man',
        animationPreset: 'earth',
        tags: ['crown'],
    },
    {
        id: 'gaunter_o_dimm',
        name: "Gaunter O'Dimm",
        nameAr: 'غونتر أوديم',
        attack: 19,
        defense: 19,
        race: 'demon',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'The Witcher',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'gehrman',
        name: 'Gehrman, the First Hunter',
        nameAr: 'غيرمان، الصياد الأول',
        attack: 19,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bloodborne',
        specialAbility: 'صياد الوحوش — فوز مضمون أمام الوحوش',
        characterAbilityId: 'gehrman_monster_hunter',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'giyu_tomioka',
        name: 'Giyu Tomioka',
        nameAr: 'غيو توميوكا',
        attack: 18,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Demon Slayer',
        animationPreset: 'water',
        tags: ['crown'],
    },
    {
        id: 'gol_d_roger',
        name: 'Gol D. Roger',
        nameAr: 'غول دي روجر',
        attack: 22,
        defense: 19,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'gwyn',
        name: 'Gwyn, Lord of Cinder',
        nameAr: 'غوين، لورد الرماد',
        attack: 21,
        defense: 18,
        race: 'undead',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Dark Souls',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'igneel',
        name: 'Igneel',
        nameAr: 'إغنيل',
        attack: 20,
        defense: 20,
        race: 'dragon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Fairy Tail',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'ken_kaneki',
        name: 'Ken Kaneki',
        nameAr: 'كين كانيكي',
        attack: 19,
        defense: 17,
        race: 'monster',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Tokyo Ghoul',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'kishou_arima',
        name: 'Kishou Arima',
        nameAr: 'كيشو أريما',
        attack: 19,
        defense: 18,
        race: 'human',
        cardClass: 'swordsman',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Tokyo Ghoul',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'klein_moretti',
        name: 'Klein Moretti',
        nameAr: 'كلاين موريتي',
        attack: 20,
        defense: 19,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Lord of the Mysteries',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'kyojuro_rengoku',
        name: 'Kyojuro Rengoku',
        nameAr: 'كيوجورو رينغوكو',
        attack: 19,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Demon Slayer',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'lady_maria',
        name: 'Lady Maria',
        nameAr: 'اللميدي ماريا ',
        attack: 19,
        defense: 17,
        race: 'undead',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'Bloodborne',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'laurence',
        name: 'Laurence, the First Vicar',
        nameAr: 'لورنس، النائب الأول',
        attack: 20,
        defense: 18,
        race: 'monster',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bloodborne',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'lilith',
        name: 'Lilith',
        nameAr: 'ليليث',
        attack: 20,
        defense: 19,
        race: 'demon',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'Diablo',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'ludwig',
        name: 'Ludwig, the Holy Blade',
        nameAr: 'لودفيغ، النصل المقدس',
        attack: 20,
        defense: 19,
        race: 'monster',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bloodborne',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'muichiro_tokito',
        name: 'Muichiro Tokito',
        nameAr: 'مويتشيرو توكيتو',
        attack: 18,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Demon Slayer',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'paarthurnax',
        name: 'Paarthurnax',
        nameAr: 'بارثورناكس',
        attack: 19,
        defense: 20,
        race: 'dragon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'The Elder Scrolls',
        animationPreset: 'wind',
        tags: ['crown'],
    },
    {
        id: 'saitama',
        name: 'Saitama',
        nameAr: 'سايتاما',
        attack: 25,
        defense: 25,
        race: 'human',
        cardClass: 'fighter',
        element: 'earth',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'One Punch Man',
        animationPreset: 'earth',
        tags: ['crown'],
    },
    {
        id: 'satella',
        name: 'Satella',
        nameAr: 'ساتيلا',
        attack: 21,
        defense: 20,
        race: 'elf',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'Re:Zero',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'the_hunter',
        name: 'The Hunter',
        nameAr: 'الصياد',
        attack: 19,
        defense: 18,
        race: 'human',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bloodborne',
        animationPreset: 'fire',
        tags: ['crown'],
    },
];
