export const COMMON_IMAGES: Record<string, any> = {
    coby: require('./coby.png'),
    hiking_bear: require('./Hiking_Bear.png'),
    yosaku: require('./yosaku.png'),
    johnny: require('./johnny.png'),
    ebisu: require('./ebisu.png'),
    konohamaru: require('./konohamaru.png'),
    bulma: require('./bulma.png'),
    hitch_dreyse: require('./hitch_dreyse.png'),
    king: require('./king.png'),
    the_plain_doll: require('./the_plain_doll.png'),
    happy: require('./happy.png'),
    mineta: require('./mineta.png'),
    chopper: require('./Chopper.png'),
    brook: require('./Brook.png'),
    mob: require('./Mob.png'),
    ten_ten: require('./Tenten.png'),
    choji_akimichi: require('./Choji_Akimichi.png'),
    hinata_hyuga: require('./Hinata_Hyuga.png'),
    ino_yamanaka: require('./ino_yamanaka.png'),
    orihime_inoue: require('./orihime_inoue.png'),
    sinon: require('./Sinon.png'),
    emilia: require('./Emilia.png'),
    kaya: require('./Kaya.png'),
    alvida: require('./Alvida.png'),
    cabaji: require('./Cabaji.png'),
    mr_3: require('./mr_3.png'),
    miss_doublefinger: require('./miss_doublefinger.png'),
    yonji: require('./Yonji.png'),
    iruka: require('./Iruka.png'),
    kurenai: require('./Kurenai.png'),
    anko: require('./Anko.png'),
    winry_rockbell: require('./winry_rockbell.png'),
    yui_sao: require('./yui_sao.png'),
    wiz: require('./Wiz.png'),
    violet_evergarden: require('./violet_evergarden.png'),
    master_roshi: require('./master_roshi.png'),
    leorio: require('./leorio.png'),
    nami: require('./nami.png'),
};

/** فيديوهات الكروت العادية — mp4 / webm */
export const COMMON_VIDEOS: Record<string, any> = {
    misa_amane: require('./Misa_Amane.mp4'),
    Turin_Turambar: require('../special/Turin_Turambar.mp4'),
};
