export const RARE_IMAGES: Record<string, any> = {
    barry_the_chopper: require('./barry_the_chopper.png'),
    coby: require('./coby.png'),
    dende: require('./dende.png'),
    dr_cossack: require('./dr_cossack.png'),
    emlyn_white: require('./emlyn_white.png'),
    falco_grice: require('./falco_grice.png'),
    franky: require('./franky.png'),
    gon_freecss: require('./Gon_Freecss.png'),
    krillin: require('./krillin.png'),
    master_roshi: require('./master_roshi.png'),
    rundelhaus: require('./rundelhaus.jpg'),
    sakura_haruno: require('./sakura_haruno.png'),
    sasha_braus: require('./sasha_braus.png'),
    silica: require('./silica.png'),
    subaru_natsuki: require('./Subaru_Natsuki.jpg'),
    suspicious_beggar: require('./suspicious_beggar.png'),
    tien_shinhan: require('./tien_shinhan.png'),
    tony_tony_chopper: require('./tony_tony_chopper.png'),
    usopp: require('./usopp.png'),
    yamcha: require('./yamcha.png'),
    floki: require('./floki.png'),
};
