import { Card } from './types';

// Batch 3/6 — Naruto
export const CARDS_BATCH_3: Card[] = [
    {
        id: 'konohamaru_sarutobi',
        name: 'Konohamaru Sarutobi',
        nameAr: 'كونوهاماروا ساروتوبي',
        attack: 4, defense: 4,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'common', stars: 2,
        animationPreset: 'wind',
    },
    {
        id: 'rock_lee',
        name: 'Rock Lee',
        nameAr: 'روك لي',
        attack: 10, defense: 9,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'wind',
    },
    {
        id: 'ten_ten',
        name: 'Tenten',
        nameAr: 'تنتن',
        attack: 9, defense: 8,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'wind',
    },
    {
        id: 'shikamaru_nara',
        name: 'Shikamaru Nara',
        nameAr: 'شيكامارو نارا',
        attack: 10, defense: 10,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'choji_akimichi',
        name: 'Choji Akimichi',
        nameAr: 'شوجي أكيميشي',
        attack: 11, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'neji_hyuga',
        name: 'Neji Hyuga',
        nameAr: 'نيجي هيوغا',
        attack: 13, defense: 12,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'hinata_hyuga',
        name: 'Hinata Hyuga',
        nameAr: 'هيناتا هيوغا',
        attack: 12, defense: 13,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'ino_yamanaka',
        name: 'Ino Yamanaka',
        nameAr: 'إينو ياماناكا',
        attack: 11, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'temari',
        name: 'Temari',
        nameAr: 'تيماري',
        attack: 13, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'kankuro',
        name: 'Kankuro',
        nameAr: 'كانكورو',
        attack: 12, defense: 12,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'killer_bee',
        name: 'Killer Bee',
        nameAr: 'كيلر بي',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'tsunade_senju',
        name: 'Tsunade Senju',
        nameAr: 'تسونادي سنجو',
        attack: 14, defense: 15,
        gender: 'female',
        race: 'human', cardClass: 'mage', element: 'fire',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'jiraiya',
        name: 'Jiraiya',
        nameAr: 'جيرايا',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'orochimaru',
        name: 'Orochimaru',
        nameAr: 'أوروشيمارو',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'gaara',
        name: 'Gaara',
        nameAr: 'غارا',
        attack: 16, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'minato_namikaze',
        name: 'Minato Namikaze',
        nameAr: 'ميناتو ناميكازي',
        attack: 17, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'itachi_uchiha',
        name: 'Itachi Uchiha',
        nameAr: 'إيتاشي أوتشيها',
        attack: 17, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'nagato_uzumaki',
        name: 'Nagato Uzumaki',
        nameAr: 'ناغاتو أوزوماكي',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'madara_uchiha',
        name: 'Madara Uchiha',
        nameAr: 'مادارا أوتشيها',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'obito_uchiha',
        name: 'Obito Uchiha',
        nameAr: 'أوبيتو أوتشيها',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'hashirama_senju',
        name: 'Hashirama Senju',
        nameAr: 'هاشيراما سنجو',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'tobirama_senju',
        name: 'Tobirama Senju',
        nameAr: 'توبيراما سنجو',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'hiruzen_sarutobi',
        name: 'Hiruzen Sarutobi',
        nameAr: 'هيروزن ساروتوبي',
        attack: 16, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'sasuke_uchiha',
        name: 'Sasuke Uchiha',
        nameAr: 'ساسوكي أوتشيها',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'naruto_uzumaki',
        name: 'Naruto Uzumaki',
        nameAr: 'ناروتو أوزوماكي',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'pain_rikudo',
        name: 'Pain (Six Paths)',
        nameAr: 'بين (المسارات الست)',
        attack: 18, defense: 17,
        race: 'demon', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'kaguya_otsutsuki',
        name: 'Kaguya Otsutsuki',
        nameAr: 'كاغويا أوتسوتسوكي',
        gender: 'female',
        attack: 19, defense: 18,
        race: 'demon', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'isshiki_otsutsuki',
        name: 'Isshiki Otsutsuki',
        nameAr: 'إيشيكي أوتسوتسوكي',
        attack: 19, defense: 18,
        race: 'demon', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
];
