import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 2/6 — Dragon Ball, AoT, Death Note, Demon Slayer
// Updated: piccolo rarity legendary→epic (from Excel v4)

export const CARDS_BATCH_2: Card[] = [
{
  id: 'yamcha',
  nameAr: 'يامتشا',
  universe: 'Dragon Ball',
  attack: 6, defense: 6,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'rare', stars: 3,
  animationPreset: 'fire',
},
{
  id: 'tien_shinhan',
  nameAr: 'تيان شينهان',
  universe: 'Dragon Ball',
  attack: 8, defense: 9,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'rare', stars: 3,
  animationPreset: 'fire',
},
{
  id: 'krillin',
  nameAr: 'كريلين',
  universe: 'Dragon Ball',
  attack: 15, defense: 13,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'master_roshi',
  nameAr: 'الماستر روشي',
  universe: 'Dragon Ball',
  attack: 12, defense: 11,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'piccolo',
  nameAr: 'بيكولو',
  universe: 'Dragon Ball',
  attack: 18, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'trunks',
  nameAr: 'ترانكس',
  universe: 'Dragon Ball',
  attack: 17, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'gohan',
  nameAr: 'غوهان',
  universe: 'Dragon Ball',
  attack: 16, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'cell',
  nameAr: 'سيل',
  universe: 'Dragon Ball',
  attack: 17, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'frieza',
  nameAr: 'فريزا',
  universe: 'Dragon Ball',
  attack: 17, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'vegeta',
  nameAr: 'فيجيتا',
  universe: 'Dragon Ball',
  attack: 17, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'broly',
  nameAr: 'بروللي',
  universe: 'Dragon Ball',
  attack: 18, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'son_goku',
  nameAr: 'غوكو',
  universe: 'Dragon Ball',
  attack: 18, defense: 17,
  race: 'orc', cardClass: 'warrior', element: 'fire',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'fire',
},
{
  id: 'hitch_dreyse',
  nameAr: 'هيتش دريس',
  universe: 'Attack on Titan',
  attack: 1, defense: 1,
  race: 'human', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'common', stars: 1,
  animationPreset: 'default',
},
{
  id: 'sasha_braus',
  nameAr: 'ساشا براوس',
  universe: 'Attack on Titan',
  attack: 8, defense: 6,
  race: 'human', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'rare', stars: 3,
  animationPreset: 'default',
},
{
  id: 'falco_grice',
  nameAr: 'فالكو غرايس',
  universe: 'Attack on Titan',
  attack: 9, defense: 7,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'rare', stars: 3,
  animationPreset: 'default',
},
{
  id: 'armin_arlert',
  nameAr: 'أرمين أرليرت',
  universe: 'Attack on Titan',
  attack: 13, defense: 11,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'default',
},
{
  id: 'bertholdt_hoover',
  nameAr: 'بيرتولدت هوفر',
  universe: 'Attack on Titan',
  attack: 12, defense: 12,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'default',
},
{
  id: 'porco_galliard',
  nameAr: 'بوركو غاليارد',
  universe: 'Attack on Titan',
  attack: 14, defense: 11,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'default',
},
{
  id: 'annie_leonhart',
  nameAr: 'آني ليونهارت',
  universe: 'Attack on Titan',
  attack: 14, defense: 11,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'default',
},
{
  id: 'mikasa_ackerman',
  nameAr: 'ميكاسا أكرمان',
  universe: 'Attack on Titan',
  attack: 15, defense: 14,
  race: 'human', cardClass: 'warrior', element: 'earth',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'default',
},
{
  id: 'reiner_braun',
  nameAr: 'راينر براون',
  universe: 'Attack on Titan',
  attack: 16, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'default',
},
{
  id: 'zeke_yeager',
  nameAr: 'زيك ييغر',
  universe: 'Attack on Titan',
  attack: 16, defense: 16,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'default',
},
{
  id: 'eren_yeager',
  nameAr: 'إيرين ييغر',
  universe: 'Attack on Titan',
  attack: 16, defense: 17,
  race: 'orc', cardClass: 'warrior', element: 'earth',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'default',
},
{
  id: 'levi_ackerman',
  nameAr: 'ليفي أكرمان',
  universe: 'Attack on Titan',
  attack: 18, defense: 16,
  race: 'human', cardClass: 'warrior', element: 'earth',
  tags: ["sword", "crown"],
  rarity: 'legendary', stars: 5,
  animationPreset: 'default',
},
{
  id: 'misa_amane',
  nameAr: 'ميسا أماني',
  universe: 'Death Note',
  attack: 1, defense: 2,
  race: 'human', cardClass: 'warrior', element: 'ice',
  tags: ["sword"],
  rarity: 'common', stars: 1,
  animationPreset: 'ice',
  rageMode: {
    enabled: true,
    rageNameAr: 'عيون الشينيغامي',
    rageAttackBoost: 10,
    rageDefenseBoost: 8,
    oncePer: 'match',
  },
},
{
  id: 'inosuke_hashibira',
  nameAr: 'إينوسوكي هاشيبيرا',
  universe: 'Demon Slayer',
  attack: 13, defense: 11,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'zenitsu_agatsuma',
  nameAr: 'زينيتسو أغاتسوما',
  universe: 'Demon Slayer',
  attack: 13, defense: 11,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'nezuko_kamado',
  nameAr: 'نيزوكو كامادو',
  universe: 'Demon Slayer',
  attack: 13, defense: 11,
  race: 'demon', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
  cardEffects: ['poison'],
},
{
  id: 'shinobu_kocho',
  nameAr: 'شينوبو كوتشو',
  universe: 'Demon Slayer',
  attack: 12, defense: 11,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'tanjiro_kamado',
  nameAr: 'تانجيرو كامادو',
  universe: 'Demon Slayer',
  attack: 15, defense: 12,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'mitsuri_kanroji',
  nameAr: 'ميتسوري كانروجي',
  universe: 'Demon Slayer',
  attack: 13, defense: 14,
  race: 'human', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
},
{
  id: 'gyutaro',
  nameAr: 'غيوتارو',
  universe: 'Demon Slayer',
  attack: 14, defense: 13,
  race: 'demon', cardClass: 'warrior', element: 'fire',
  tags: ["sword"],
  rarity: 'epic', stars: 4,
  animationPreset: 'fire',
  cardEffects: ['poison'],
},
];
