import { Card } from './types';

// Batch 3/6 — 39 cards
export const CARDS_BATCH_3: Card[] = [
    {
        id: 'akaza',
        name: 'Akaza',
        nameAr: 'أكازا',
        attack: 16, defense: 14,
        race: 'demon', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'doma',
        name: 'Doma',
        nameAr: 'دوما',
        attack: 17, defense: 15,
        race: 'demon', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'kokushibo',
        name: 'Kokushibo',
        nameAr: 'كوكوشيبو',
        attack: 18, defense: 16,
        race: 'demon', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'muzan_kibutsuji',
        name: 'Muzan Kibutsuji',
        nameAr: 'موزان كيبوتسوجي',
        attack: 19, defense: 17,
        race: 'demon', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'konohamaru_sarutobi',
        name: 'Konohamaru Sarutobi',
        nameAr: 'كونوهاماروا ساروتوبي',
        attack: 4, defense: 4,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'common', stars: 2,
        animationPreset: 'wind',
    },
    {
        id: 'ten_ten',
        name: 'Tenten',
        nameAr: 'تنتن',
        attack: 9, defense: 8,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'wind',
    },
    {
        id: 'shikamaru_nara',
        name: 'Shikamaru Nara',
        nameAr: 'شيكامارو نارا',
        attack: 10, defense: 10,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'choji_akimichi',
        name: 'Choji Akimichi',
        nameAr: 'شوجي أكيميشي',
        attack: 11, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'rare', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'neji_hyuga',
        name: 'Neji Hyuga',
        nameAr: 'نيجي هيوغا',
        attack: 13, defense: 12,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'hinata_hyuga',
        name: 'Hinata Hyuga',
        nameAr: 'هيناتا هيوغا',
        attack: 12, defense: 13,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'ino_yamanaka',
        name: 'Ino Yamanaka',
        nameAr: 'إينو ياماناكا',
        attack: 11, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'temari',
        name: 'Temari',
        nameAr: 'تيماري',
        attack: 13, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'kankuro',
        name: 'Kankuro',
        nameAr: 'كانكورو',
        attack: 12, defense: 12,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'killer_bee',
        name: 'Killer Bee',
        nameAr: 'كيلر بي',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'tsunade_senju',
        name: 'Tsunade Senju',
        nameAr: 'تسونادي سنجو',
        attack: 14, defense: 15,
        gender: 'female',
        race: 'human', cardClass: 'mage', element: 'fire',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'nagato_uzumaki',
        name: 'Nagato Uzumaki',
        nameAr: 'ناغاتو أوزوماكي',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'obito_uchiha',
        name: 'Obito Uchiha',
        nameAr: 'أوبيتو أوتشيها',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'tobirama_senju',
        name: 'Tobirama Senju',
        nameAr: 'توبيراما سنجو',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'hiruzen_sarutobi',
        name: 'Hiruzen Sarutobi',
        nameAr: 'هيروزن ساروتوبي',
        attack: 16, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'wind',
    },
    {
        id: 'pain_rikudo',
        name: 'Pain (Six Paths)',
        nameAr: 'بين (المسارات الست)',
        attack: 18, defense: 17,
        race: 'demon', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'kaguya_otsutsuki',
        name: 'Kaguya Otsutsuki',
        nameAr: 'كاغويا أوتسوتسوكي',
        gender: 'female',
        attack: 19, defense: 18,
        race: 'demon', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'isshiki_otsutsuki',
        name: 'Isshiki Otsutsuki',
        nameAr: 'إيشيكي أوتسوتسوكي',
        attack: 19, defense: 18,
        race: 'demon', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'coby',
        name: 'Coby',
        nameAr: 'كوبي',
        attack: 3, defense: 3,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'water',
    },
    {
        id: 'smoker',
        name: 'Smoker',
        nameAr: 'سموكر',
        attack: 13, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'crocodile',
        name: 'Crocodile',
        nameAr: 'كروكودايل',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'doflamingo',
        name: 'Doflamingo',
        nameAr: 'دوفلامينغو',
        attack: 15, defense: 14,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'trafalgar_law',
        name: 'Trafalgar Law',
        nameAr: 'ترافالغار لو',
        attack: 15, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'elf_zoro',
        name: 'Roronoa Zoro',
        nameAr: 'رورونوا زورو',
        attack: 17, defense: 15,
        race: 'elf', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'blackbeard',
        name: 'Marshall D. Teach',
        nameAr: 'مارشال دي تيتش',
        attack: 18, defense: 16,
        race: 'orc', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'luffy',
        name: 'Monkey D. Luffy',
        nameAr: 'مانكي دي لوفي',
        attack: 18, defense: 17,
        race: 'orc', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'orihime_inoue',
        name: 'Orihime Inoue',
        nameAr: 'أوريهيمي إينوي',
        attack: 6, defense: 8,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'water',
    },
    {
        id: 'rukia_kuchiki',
        name: 'Rukia Kuchiki',
        nameAr: 'روكيا كوتشيكي',
        attack: 12, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'yoruichi_shihoin',
        name: 'Yoruichi Shihoin',
        nameAr: 'يوروئيتشي شيهوين',
        attack: 17,
        defense: 15,
        race: 'human',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'Bleach',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'nelliel_tu',
        name: 'Nelliel Tu Odelschwanck',
        nameAr: 'نيليل تو أوديلشفانك',
        attack: 14, defense: 13,
        gender: 'female',
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'ulquiorra_cifer',
        name: 'Ulquiorra Cifer',
        nameAr: 'أولكيورا سيفر',
        attack: 18,
        defense: 17,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'grimmjow_jaegerjaquez',
        name: 'Grimmjow Jaegerjaquez',
        nameAr: 'غريمجو ياغيرياكيز',
        attack: 16, defense: 14,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'sosuke_aizen',
        name: 'Sosuke Aizen',
        nameAr: 'سوسوكي أيزن',
        attack: 18, defense: 17,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'ichigo_kurosaki',
        name: 'Ichigo Kurosaki',
        nameAr: 'إيشيغو كوروساكي',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'killua_zoldyck',
        name: 'Killua Zoldyck',
        nameAr: 'كيلوا زولديك',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'fighter',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Hunter x Hunter',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
];
