import { Card } from './types';

// Batch 7/8 — 49 cards (orphaned-media recovery: common + rare + epic first half)
export const CARDS_BATCH_7: Card[] = [
    // ═══════════════════════════════════════════════════════════════════════
    // COMMON  (stars 1–2)
    // ═══════════════════════════════════════════════════════════════════════
    {
        id: 'bulma',
        name: 'Bulma',
        nameAr: 'بولما',
        attack: 3,
        defense: 5,
        race: 'human',
        cardClass: 'healer',
        element: 'earth',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Dragon Ball',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'ebisu',
        name: 'Ebisu',
        nameAr: 'إيبيسو',
        attack: 5,
        defense: 5,
        race: 'human',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'common',
        stars: 2,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'happy',
        name: 'Happy',
        nameAr: 'هابي',
        attack: 2,
        defense: 3,
        race: 'monster',
        cardClass: 'healer',
        element: 'wind',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'Fairy Tail',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'hiking_bear',
        name: 'Hiking Bear',
        nameAr: 'الدب المتجول',
        attack: 3,
        defense: 4,
        race: 'monster',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'king',
        name: 'King',
        nameAr: 'كينغ',
        attack: 1,
        defense: 3,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'One Punch Man',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'mineta',
        name: 'Mineta',
        nameAr: 'مينيتا',
        attack: 3,
        defense: 4,
        race: 'human',
        cardClass: 'fighter',
        element: 'earth',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'the_plain_doll',
        name: 'The Plain Doll',
        nameAr: 'الدمية',
        attack: 2,
        defense: 6,
        race: 'human',
        cardClass: 'healer',
        element: 'water',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Bloodborne',
        animationPreset: 'default',
        tags: [],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // RARE  (stars 3)
    // ═══════════════════════════════════════════════════════════════════════
    {
        id: 'barry_the_chopper',
        name: 'Barry the Chopper',
        nameAr: 'باري ذا تشوبر',
        attack: 10,
        defense: 8,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'dende',
        name: 'Dende',
        nameAr: 'دندي',
        attack: 5,
        defense: 9,
        race: 'orc',
        cardClass: 'healer',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Dragon Ball',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'dr_cossack',
        name: 'Dr. Cossack',
        nameAr: 'د. كوساك',
        attack: 9,
        defense: 10,
        race: 'human',
        cardClass: 'mage',
        element: 'lightning',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Mega Man',
        animationPreset: 'lightning',
        tags: [],
    },
    {
        id: 'emlyn_white',
        name: 'Emlyn White',
        nameAr: 'إيملن وايت',
        attack: 8,
        defense: 12,
        race: 'human',
        cardClass: 'healer',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Lord of the Mysteries',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'floki',
        name: 'Floki',
        nameAr: 'فلوكي',
        attack: 11,
        defense: 9,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Vinland Saga',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'rundelhaus',
        name: 'Rundelhaus',
        nameAr: 'رنديلهاوس',
        attack: 12,
        defense: 10,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Log Horizon',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'silica',
        name: 'Silica',
        nameAr: 'سيليكا',
        attack: 9,
        defense: 10,
        race: 'human',
        cardClass: 'swordsman',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Sword Art Online',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'suspicious_beggar',
        name: 'Suspicious Beggar',
        nameAr: 'المتسول المشبوه',
        attack: 11,
        defense: 8,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Bloodborne',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'tony_tony_chopper',
        name: 'Tony Tony Chopper',
        nameAr: 'توني توني تشوبر',
        attack: 7,
        defense: 11,
        race: 'orc',
        cardClass: 'healer',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // EPIC — first half  (stars 4)
    // ═══════════════════════════════════════════════════════════════════════
    {
        id: 'alger_wilson',
        name: 'Alger Wilson',
        nameAr: 'ألجر ويلسون',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Lord of the Mysteries',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'amaimon',
        name: 'Amaimon',
        nameAr: 'أمايمون',
        attack: 15,
        defense: 13,
        race: 'demon',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Blue Exorcist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'aoi_todo',
        name: 'Aoi Todo',
        nameAr: 'أوي تودو',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'askeladd',
        name: 'Askeladd',
        nameAr: 'أسكيلاد',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Vinland Saga',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'asuka_langley',
        name: 'Asuka Langley',
        nameAr: 'أسوكا لانغلي',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Evangelion',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'bass',
        name: 'Bass',
        nameAr: 'باس',
        attack: 16,
        defense: 15,
        race: 'robot',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Mega Man',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'black_maria',
        name: 'Black Maria',
        nameAr: 'بلاك ماريا',
        attack: 14,
        defense: 15,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'clare',
        name: 'Clare',
        nameAr: 'كلير',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Claymore',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'eileen_the_crow',
        name: 'Eileen the Crow',
        nameAr: 'إيلين الغراب',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Bloodborne',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'endeavor',
        name: 'Endeavor',
        nameAr: 'إنديفور',
        attack: 17,
        defense: 15,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'eustass_kid',
        name: 'Eustass Kid',
        nameAr: 'يوستاس كيد',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'father_gascoigne',
        name: 'Father Gascoigne',
        nameAr: 'الأب غاسكوين',
        attack: 16,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Bloodborne',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'genos',
        name: 'Genos',
        nameAr: 'جينوس',
        attack: 16,
        defense: 13,
        race: 'robot',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'One Punch Man',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'hawks',
        name: 'Hawks',
        nameAr: 'هوكس',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'heathcliff_kayaba',
        name: 'Heathcliff Kayaba',
        nameAr: 'هيثكليف كايابا',
        attack: 16,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Sword Art Online',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'hector',
        name: 'Hector',
        nameAr: 'هيكتور',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Castlevania',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'illumi_zoldyck',
        name: 'Illumi Zoldyck',
        nameAr: 'إلومي زولديك',
        attack: 16,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Hunter x Hunter',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'impa',
        name: 'Impa',
        nameAr: 'إمبا',
        attack: 14,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Zelda',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'isaac',
        name: 'Isaac',
        nameAr: 'إسحاق',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Castlevania',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'izuku_midoriya',
        name: 'Izuku Midoriya',
        nameAr: 'إيزوكو ميدوريا',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'kakashi_hatake',
        name: 'Kakashi Hatake',
        nameAr: 'كاكاشي هاتاكي',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'swordsman',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'kamina',
        name: 'Kamina',
        nameAr: 'كامينا',
        attack: 15,
        defense: 12,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Gurren Lagann',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'katsuki_bakugo',
        name: 'Katsuki Bakugo',
        nameAr: 'كاتسوكي باكوغو',
        attack: 16,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'My Hero Academia',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'kaworu_nagisa',
        name: 'Kaworu Nagisa',
        nameAr: 'كاوورو ناغيسا',
        attack: 14,
        defense: 15,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Evangelion',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'kite',
        name: 'Kite',
        nameAr: 'كايت',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Hunter x Hunter',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'lich_general',
        name: 'Lich General',
        nameAr: 'الجنرال ليتش',
        attack: 15,
        defense: 14,
        race: 'undead',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Fantasy',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'link',
        name: 'Link',
        nameAr: 'لينك',
        attack: 15,
        defense: 15,
        race: 'elf',
        cardClass: 'swordsman',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Zelda',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'lordgenome',
        name: 'Lordgenome',
        nameAr: 'لوردجينوم',
        attack: 17,
        defense: 16,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Gurren Lagann',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'mega_man',
        name: 'Mega Man',
        nameAr: 'ميغا مان',
        attack: 15,
        defense: 15,
        race: 'robot',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Mega Man',
        animationPreset: 'lightning',
        tags: [],
    },
    {
        id: 'might_guy',
        name: 'Might Guy',
        nameAr: 'مايت غاي',
        attack: 17,
        defense: 14,
        race: 'human',
        cardClass: 'fighter',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'nyanta',
        name: 'Nyanta',
        nameAr: 'نيانتا',
        attack: 14,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Log Horizon',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'ornstein',
        name: 'Ornstein',
        nameAr: 'أورنستين',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'swordsman',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Dark Souls',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'pandoras_actor',
        name: 'Pandora\'s Actor',
        nameAr: 'باندوراز أكتر',
        attack: 14,
        defense: 15,
        race: 'demon',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Overlord',
        animationPreset: 'default',
        tags: [],
    },
];
