import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 1/6 — 54 cards (updated from Excel v4)
// Universes: One Piece, Naruto, Dragon Ball

export const CARDS_BATCH_1: Card[] = [
  {
    id: 'yosaku',
    nameAr: 'يوساكو',
    universe: 'One Piece',
    attack: 2, defense: 1,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    nameAr: 'جوني',
    universe: 'One Piece',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'nami',
    nameAr: 'نامي',
    universe: 'One Piece',
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'coby',
    nameAr: 'كوبي',
    universe: 'One Piece',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'usopp',
    nameAr: 'أوسوب',
    universe: 'One Piece',
    attack: 8, defense: 6,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["arrow", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'tony_tony_chopper',
    nameAr: 'توني توني تشوبر',
    universe: 'One Piece',
    attack: 9, defense: 6,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'franky',
    nameAr: 'فرانكي',
    universe: 'One Piece',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'eustass_kid',
    nameAr: 'يوستاس كيد',
    universe: 'One Piece',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'crocodile',
    nameAr: 'كروكودايل',
    universe: 'One Piece',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'donquixote_doflamingo',
    nameAr: 'دوفلامينغو',
    universe: 'One Piece',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'black_maria',
    nameAr: 'بلاك ماريا',
    universe: 'One Piece',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'trafalgar_law',
    nameAr: 'ترافلغار لاو',
    universe: 'One Piece',
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'jinbe',
    nameAr: 'جينبي',
    universe: 'One Piece',
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'sabo',
    nameAr: 'سابو',
    universe: 'One Piece',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'sanji',
    nameAr: 'سانجي',
    universe: 'One Piece',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
    specialAbility: 'يخسر من جميع النساء',
  },
  {
    id: 'roronoa_zoro',
    nameAr: 'رورونوا زورو',
    universe: 'One Piece',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'dracule_mihawk',
    nameAr: 'دراكيول ميهوك',
    universe: 'One Piece',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
    specialAbility: 'ينتصر على جميع السيافين',
  },
  {
    id: 'monkey_d_luffy',
    nameAr: 'مونكي دي لوفي',
    universe: 'One Piece',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'gol_d_roger',
    nameAr: 'غول دي روجر',
    universe: 'One Piece',
    attack: 17, defense: 18,
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'kaido',
    nameAr: 'كايدو',
    universe: 'One Piece',
    attack: 19, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'water',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'ebisu',
    nameAr: 'إيبيسو',
    universe: 'Naruto',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    nameAr: 'كونوهامارو',
    universe: 'Naruto',
    attack: 5, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'default',
  },
  {
    id: 'sakura_haruno',
    nameAr: 'ساكورا هارونو',
    universe: 'Naruto',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'healer', element: 'wind',
    tags: ["magic", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
    specialAbility: 'في حال الفوز زياده الصحه ( 1 )',
  },
  {
    id: 'neji_hyuga',
    nameAr: 'نيجي هيوغا',
    universe: 'Naruto',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'rock_lee',
    nameAr: 'روك لي',
    universe: 'Naruto',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'killer_bee',
    nameAr: 'كيلر بي',
    universe: 'Naruto',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'gaara',
    nameAr: 'غارا',
    universe: 'Naruto',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'tsunade',
    nameAr: 'تسونادي',
    universe: 'Naruto',
    attack: 13, defense: 13,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'orochimaru',
    nameAr: 'أوروتشيمارو',
    universe: 'Naruto',
    attack: 15, defense: 13,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'kakashi_hatake',
    nameAr: 'كاكاشي هاتاكي',
    universe: 'Naruto',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'jiraiya',
    nameAr: 'جيرايا',
    universe: 'Naruto',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'might_guy',
    nameAr: 'مايت غاي',
    universe: 'Naruto',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'obito_uchiha',
    nameAr: 'أوبيتو أوتشيها',
    universe: 'Naruto',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'itachi_uchiha',
    nameAr: 'إيتاتشي أوتشيها',
    universe: 'Naruto',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'pain_nagato',
    nameAr: 'باين (ناغاتو)',
    universe: 'Naruto',
    attack: 16, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'minato_namikaze',
    nameAr: 'ميناتو ناميكازي',
    universe: 'Naruto',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'sasuke_uchiha',
    nameAr: 'ساسكي أوتشيها',
    universe: 'Naruto',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'naruto_uzumaki',
    nameAr: 'ناروتو أوزوماكي',
    universe: 'Naruto',
    attack: 19, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'madara_uchiha',
    nameAr: 'مادارا أوتشيها',
    universe: 'Naruto',
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'bulma',
    nameAr: 'بولما',
    universe: 'Dragon Ball',
    attack: 1, defense: 0,
    race: 'human', cardClass: 'mage', element: 'fire',
    tags: ["magic"],
    rarity: 'common', stars: 1,
    animationPreset: 'fire',
  },
  {
    id: 'dende',
    nameAr: 'ديندي',
    universe: 'Dragon Ball',
    attack: 6, defense: 6,
    race: 'elf', cardClass: 'healer', element: 'fire',
    tags: ["magic", "crown"],
    rarity: 'rare', stars: 3,
    animationPreset: 'fire',
  },
  {
    id: 'piccolo',
    nameAr: 'بيكولو',
    universe: 'Dragon Ball',
    attack: 18, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
  },
  {
    id: 'trunks',
    nameAr: 'ترانكس',
    universe: 'Dragon Ball',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'cell',
    nameAr: 'سيل',
    universe: 'Dragon Ball',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'frieza',
    nameAr: 'فريزا',
    universe: 'Dragon Ball',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'gohan',
    nameAr: 'غوهان',
    universe: 'Dragon Ball',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'vegeta',
    nameAr: 'فيغيتا',
    universe: 'Dragon Ball',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'broly',
    nameAr: 'برولي',
    universe: 'Dragon Ball',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'son_goku',
    nameAr: 'سون غوكو',
    universe: 'Dragon Ball',
    attack: 18, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
];
