import { Card } from './types';

// Batch 4/6 — One Piece
export const CARDS_BATCH_4: Card[] = [
    {
        id: 'coby',
        name: 'Coby',
        nameAr: 'كوبي',
        attack: 3, defense: 3,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'water',
    },    {
        id: 'smoker',
        name: 'Smoker',
        nameAr: 'سموكر',
        attack: 13, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'crocodile',
        name: 'Crocodile',
        nameAr: 'كروكودايل',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'doflamingo',
        name: 'Doflamingo',
        nameAr: 'دوفلامينغو',
        attack: 15, defense: 14,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'trafalgar_law',
        name: 'Trafalgar Law',
        nameAr: 'ترافالغار لو',
        attack: 15, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'elf_zoro',
        name: 'Roronoa Zoro',
        nameAr: 'رورونوا زورو',
        attack: 17, defense: 15,
        race: 'elf', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },    {
        id: 'blackbeard',
        name: 'Marshall D. Teach',
        nameAr: 'مارشال دي تيتش',
        attack: 18, defense: 16,
        race: 'orc', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'luffy',
        name: 'Monkey D. Luffy',
        nameAr: 'مانكي دي لوفي',
        attack: 18, defense: 17,
        race: 'orc', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
];
