import { Card } from './types';

// Batch 4/6 — 39 cards
export const CARDS_BATCH_4: Card[] = [
    {
        id: 'kurapika',
        name: 'Kurapika',
        nameAr: 'كورابيكا',
        attack: 14, defense: 13,
        race: 'elf', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'hisoka_morow',
        name: 'Hisoka Morow',
        nameAr: 'هيسوكا مورو',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'meruem',
        name: 'Meruem',
        nameAr: 'ميروم',
        attack: 19, defense: 18,
        race: 'orc', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'gon_freecss',
        name: 'Gon Freecss',
        nameAr: 'غون فريكس',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'netero',
        name: 'Netero',
        nameAr: 'نيتيرو',
        attack: 20,
        defense: 18,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Hunter x Hunter',
        specialAbility: '',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'edward_elric',
        name: 'Edward Elric',
        nameAr: 'إدوارد إيلريك',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'roy_mustang',
        name: 'Roy Mustang',
        nameAr: 'روي موستانغ',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'alphonse_elric',
        name: 'Alphonse Elric',
        nameAr: 'ألفونس إيلريك',
        attack: 14, defense: 16,
        race: 'elf', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'kirito',
        name: 'Kirito',
        nameAr: 'كيريتو',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Sword Art Online',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'sinon',
        name: 'Sinon',
        nameAr: 'سينون',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Sword Art Online',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'alice_zuberg',
        name: 'Alice Zuberg',
        nameAr: 'أليس زوبرغ',
        attack: 15, defense: 15,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'eugeo',
        name: 'Eugeo',
        nameAr: 'أوغيو',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'emilia',
        name: 'Emilia',
        nameAr: 'إيميليا',
        attack: 14,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Re:Zero',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'subaru_natsuki',
        name: 'Subaru Natsuki',
        nameAr: 'سوبارو ناتسوكي',
        attack: 12, defense: 11,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'lightning',
    },
    {
        id: 'reinhard_van_astrea',
        name: 'Reinhard van Astrea',
        nameAr: 'راينهارد فان أستريا',
        attack: 19, defense: 18,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'ainz_ooal_gown',
        name: 'Ainz Ooal Gown',
        nameAr: 'أينز أوال غاون',
        attack: 20,
        defense: 20,
        race: 'demon',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Overlord',
        specialAbility: 'ملك الموت — يلغي كل الدفاعات',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'bam',
        name: 'Twenty-Fifth Bam',
        nameAr: 'بام الخامس والعشرون',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'rak_wraithraiser',
        name: 'Rak Wraithraiser',
        nameAr: 'راك ريذرايزر',
        attack: 16, defense: 15,
        race: 'orc', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'khun_aguero',
        name: 'Khun Aguero Agnes',
        nameAr: 'خون أغويرو أغنيس',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'mage', element: 'water',
        tags: ["magic"],
        rarity: 'rare', stars: 3,
        animationPreset: 'water',
    },
    {
        id: 'goto_ryuji',
        name: 'Goto Ryuji',
        nameAr: 'غوتو ريوجي',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'swordsman',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Solo Leveling',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'ashborn',
        name: 'Ashborn',
        nameAr: 'أشبورن',
        attack: 20,
        defense: 20,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Solo Leveling',
        specialAbility: '',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'yosaku',
        name: 'Yosaku',
        nameAr: 'يوساكو',
        attack: 3,
        defense: 3,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'johnny',
        name: 'Johnny',
        nameAr: 'جوني',
        attack: 3,
        defense: 3,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'kaya',
        name: 'Kaya',
        nameAr: 'كايا',
        attack: 1,
        defense: 2,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'common',
        stars: 1,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
];
