import type { Card } from '../lib/game/types';

// Batch 4/6 — Bleach (end) + Hunter x Hunter + Fullmetal Alchemist
export const CARDS_BATCH_4: Card[] = [
  {
    id: 'toshiro_hitsugaya',
    name: 'Toshiro Hitsugaya',
    nameAr: 'توشيرو هيتسوغايا',
    attack: 16, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'water',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'default',
  },
  {
    id: 'kenpachi_zaraki',
    name: 'Kenpachi Zaraki',
    nameAr: 'كينباتشي زاراكي',
    attack: 19, defense: 15,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'fire',
  },
  {
    id: 'yoruichi_shihoin',
    name: 'Yoruichi Shihoin',
    nameAr: 'يوروئيتشي شيهوين',
    attack: 17, defense: 15,
    gender: 'female',
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'lightning',
  },
  {
    id: 'kisuke_urahara',
    name: 'Kisuke Urahara',
    nameAr: 'كيسوكي أوراهارا',
    attack: 17, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'default',
  },
  {
    id: 'ulquiorra_cifer',
    name: 'Ulquiorra Cifer',
    nameAr: 'أولكيورا سيفر',
    attack: 18, defense: 17,
    gender: 'male',
    race: 'demon', cardClass: 'warrior', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'default',
  },
  {
    id: 'grimmjow',
    name: 'Grimmjow',
    nameAr: 'غريمجو',
    attack: 17, defense: 15,
    gender: 'male',
    race: 'demon', cardClass: 'warrior', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'default',
  },
  {
    id: 'leorio',
    name: 'Leorio',
    nameAr: 'ليوريو',
    attack: 10, defense: 10,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'Hunter x Hunter',
    animationPreset: 'fire',
  },
  {
    id: 'killua_zoldyck',
    name: 'Killua Zoldyck',
    nameAr: 'كيلوا زولديك',
    attack: 16, defense: 15,
    gender: 'male',
    race: 'human', cardClass: 'fighter', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Hunter x Hunter',
    animationPreset: 'lightning',
  },
  {
    id: 'netero',
    name: 'Netero',
    nameAr: 'نيتيرو',
    attack: 20, defense: 18,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Hunter x Hunter',
    specialAbility: 'اليد المئة وثمانية أبواب البوذية',
    animationPreset: 'default',
  },
  {
    id: 'neferpitou',
    name: 'Neferpitou',
    nameAr: 'نيفيربيتو',
    attack: 18, defense: 17,
    race: 'demon', cardClass: 'warrior', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Hunter x Hunter',
    animationPreset: 'default',
  },
  {
    id: 'winry_rockbell',
    name: 'Winry Rockbell',
    nameAr: 'وينري روكبيل',
    attack: 4, defense: 5,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: [],
    rarity: 'common', stars: 2,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'default',
  },
  {
    id: 'riza_hawkeye',
    name: 'Riza Hawkeye',
    nameAr: 'ريزا هوكآي',
    attack: 13, defense: 12,
    gender: 'female',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'fire',
  },
  {
    id: 'alex_armstrong',
    name: 'Alex Armstrong',
    nameAr: 'أليكس أرمسترونغ',
    attack: 14, defense: 15,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'default',
  },
  {
    id: 'olivier_armstrong',
    name: 'Olivier Armstrong',
    nameAr: 'أوليفييه أرمسترونغ',
    attack: 15, defense: 14,
    gender: 'female',
    race: 'human', cardClass: 'swordsman', element: 'water',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'default',
  },
  {
    id: 'scar_fma',
    name: 'Scar',
    nameAr: 'سكار',
    attack: 15, defense: 13,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'fire',
  },
  {
    id: 'envy',
    name: 'Envy',
    nameAr: 'إنفي',
    attack: 14, defense: 13,
    race: 'demon', cardClass: 'warrior', element: 'wind',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Fullmetal Alchemist',
    animationPreset: 'default',
  },
];
