import { Card } from './types';

// Batch 5/6 — Bleach / Hunter x Hunter / Fullmetal Alchemist
export const CARDS_BATCH_5: Card[] = [
    {
        id: 'orihime_inoue',
        name: 'Orihime Inoue',
        nameAr: 'أوريهيمي إينوي',
        attack: 6, defense: 8,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'water',
    },
    {
        id: 'rukia_kuchiki',
        name: 'Rukia Kuchiki',
        nameAr: 'روكيا كوتشيكي',
        attack: 12, defense: 11,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'yoruichi_shihoin',
        name: 'Yoruichi Shihoin',
        nameAr: 'يوروييشي شيهوين',
        attack: 14, defense: 13,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'nelliel_tu',
        name: 'Nelliel Tu Odelschwanck',
        nameAr: 'نيليل تو أوديلشفانك',
        attack: 14, defense: 13,
        gender: 'female',
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'ulquiorra_cifer',
        name: 'Ulquiorra Cifer',
        nameAr: 'أولكيورا سيفر',
        attack: 16, defense: 15,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'grimmjow_jaegerjaquez',
        name: 'Grimmjow Jaegerjaquez',
        nameAr: 'غريمجو ياغيرياكيز',
        attack: 16, defense: 14,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'sosuke_aizen',
        name: 'Sosuke Aizen',
        nameAr: 'سوسوكي أيزن',
        attack: 18, defense: 17,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'ichigo_kurosaki',
        name: 'Ichigo Kurosaki',
        nameAr: 'إيشيغو كوروساكي',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'killua_zoldyck',
        name: 'Killua Zoldyck',
        nameAr: 'كيلوا زولديك',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'kurapika',
        name: 'Kurapika',
        nameAr: 'كورابيكا',
        attack: 14, defense: 13,
        race: 'elf', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'leorio_paradinight',
        name: 'Leorio Paradinight',
        nameAr: 'ليوريو باراداينايت',
        attack: 12, defense: 11,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'hisoka_morow',
        name: 'Hisoka Morow',
        nameAr: 'هيسوكا مورو',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'meruem',
        name: 'Meruem',
        nameAr: 'ميروم',
        attack: 19, defense: 18,
        race: 'orc', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'gon_freecss',
        name: 'Gon Freecss',
        nameAr: 'غون فريكس',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'netero',
        name: 'Isaac Netero',
        nameAr: 'إيزاك نيتيرو',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'edward_elric',
        name: 'Edward Elric',
        nameAr: 'إدوارد إيلريك',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'roy_mustang',
        name: 'Roy Mustang',
        nameAr: 'روي موستانغ',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'alphonse_elric',
        name: 'Alphonse Elric',
        nameAr: 'ألفونس إيلريك',
        attack: 14, defense: 16,
        race: 'elf', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'pride_ling',
        name: 'King Bradley (Pride)',
        nameAr: 'الملك برادلي (برايد)',
        attack: 17, defense: 15,
        race: 'orc', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'father_fma',
        name: 'Father',
        nameAr: 'الأب',
        attack: 19, defense: 18,
        race: 'dragon', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
];
