import { Card } from './types';

// Batch 6/6 — 38 cards
export const CARDS_BATCH_6: Card[] = [
    {
        id: 'olivier_armstrong',
        name: 'Olivier Armstrong',
        nameAr: 'أوليفييه أرمسترونغ',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'scar_fma',
        name: 'Scar Fma',
        nameAr: 'سكار',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'envy',
        name: 'Envy',
        nameAr: 'إنفي',
        attack: 14,
        defense: 13,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'unknown',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'greed',
        name: 'Greed',
        nameAr: 'غريد',
        attack: 15,
        defense: 16,
        race: 'demon',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'pride_fma',
        name: 'Pride Fma',
        nameAr: 'برايد',
        attack: 17,
        defense: 16,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'leafa',
        name: 'Leafa',
        nameAr: 'ليفا',
        attack: 13,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Sword Art Online',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'yui_sao',
        name: 'Yui Sao',
        nameAr: 'يوي',
        attack: 10,
        defense: 12,
        race: 'human',
        cardClass: 'mage',
        element: 'lightning',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Sword Art Online',
        animationPreset: 'lightning',
        tags: [],
    },
    {
        id: 'kazuma',
        name: 'Kazuma',
        nameAr: 'كازوما',
        attack: 7,
        defense: 7,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'KonoSuba',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'aqua',
        name: 'Aqua',
        nameAr: 'أكوا',
        attack: 8,
        defense: 10,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'KonoSuba',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'megumin',
        name: 'Megumin',
        nameAr: 'ميغومين',
        attack: 18,
        defense: 5,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'KonoSuba',
        specialAbility: '',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'wiz',
        name: 'Wiz',
        nameAr: 'ويز',
        attack: 15,
        defense: 14,
        race: 'demon',
        cardClass: 'mage',
        element: 'water',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'KonoSuba',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'shalltear',
        name: 'Shalltear',
        nameAr: 'شالتير',
        attack: 18,
        defense: 17,
        race: 'demon',
        cardClass: 'warrior',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Overlord',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'violet_evergarden',
        name: 'Violet Evergarden',
        nameAr: 'فايوليت إيفرغاردن',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'common',
        stars: 1,
        gender: 'female',
        universe: 'Violet Evergarden',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'spike_spiegel',
        name: 'Spike Spiegel',
        nameAr: 'سبايك سبيغل',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Cowboy Bebop',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'milim_nava',
        name: 'Milim Nava',
        nameAr: 'ميليم نافا',
        attack: 20,
        defense: 18,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Tensura',
        specialAbility: '',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'shuna',
        name: 'Shuna',
        nameAr: 'شونا',
        attack: 13,
        defense: 13,
        race: 'demon',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Tensura',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'benimaru',
        name: 'Benimaru',
        nameAr: 'بينيمارو',
        attack: 17,
        defense: 15,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Tensura',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'sung_jinwoo',
        name: 'Sung Jinwoo',
        nameAr: 'سونغ جين-وو',
        attack: 20,
        defense: 19,
        race: 'human',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Solo Leveling',
        specialAbility: '',
        animationPreset: 'shadow',
        tags: ['crown'],
    },
    {
        id: 'denji',
        name: 'Denji',
        nameAr: 'دينجي',
        attack: 17,
        defense: 14,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Chainsaw Man',
        specialAbility: '',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'power',
        name: 'Power Csm',
        nameAr: 'باور',
        attack: 15,
        defense: 13,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Chainsaw Man',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'makima',
        name: 'Makima',
        nameAr: 'ماكيما',
        attack: 18,
        defense: 17,
        race: 'demon',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'Chainsaw Man',
        specialAbility: 'السيطرة — +4 هجوم وتخفيض هجوم الخصم بمقدار 4',
        characterAbilityId: 'makima_control',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'aki_hayakawa',
        name: 'Aki Hayakawa',
        nameAr: 'آكي هاياكاوا',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Chainsaw Man',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'yuta_okkotsu',
        name: 'Yuta Okkotsu',
        nameAr: 'يوتا أوكوتسو',
        attack: 18,
        defense: 17,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        specialAbility: '',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'megumi_fushiguro',
        name: 'Megumi Fushiguro',
        nameAr: 'ميغومي فوشيغورو',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'nobara_kugisaki',
        name: 'Nobara Kugisaki',
        nameAr: 'نوبارا كوغيساكي',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'epic',
        stars: 4,
        gender: 'female',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'nanami_kento',
        name: 'Nanami Kento',
        nameAr: 'ناناميه كينتو',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'swordsman',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'toge_inumaki',
        name: 'Toge Inumaki',
        nameAr: 'توغي إينوماكي',
        attack: 15,
        defense: 13,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'satoru_gojo',
        name: 'Satoru Gojo',
        nameAr: 'ساتورو غوجو',
        attack: 20,
        defense: 20,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        specialAbility: 'اللانهاية — دفاع 99 في هذه الجولة',
        characterAbilityId: 'gojo_infinity',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'ryomen_sukuna',
        name: 'Ryomen Sukuna',
        nameAr: 'ريومين سوكونا',
        attack: 20,
        defense: 19,
        race: 'demon',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        specialAbility: 'ملك اللعنات — +6 هجوم في هذه الجولة',
        characterAbilityId: 'sukuna_curse_king',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'yuji_itadori',
        name: 'Yuji Itadori',
        nameAr: 'يوجي إيتادوري',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Jujutsu Kaisen',
        animationPreset: 'fire',
        tags: ['crown'],
    },
];
