import type { Card } from '../lib/game/types';

// Batch 2/6 — One Piece (common→epic) + One Piece (legendary start)
export const CARDS_BATCH_2: Card[] = [
  {
    id: 'yosaku',
    name: 'Yosaku',
    nameAr: 'يوساكو',
    attack: 3, defense: 3,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'water',
    tags: [],
    rarity: 'common', stars: 1,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'johnny',
    name: 'Johnny',
    nameAr: 'جوني',
    attack: 3, defense: 3,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'water',
    tags: [],
    rarity: 'common', stars: 1,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'kaya',
    name: 'Kaya',
    nameAr: 'كايا',
    attack: 1, defense: 2,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'water',
    tags: [],
    rarity: 'common', stars: 1,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'alvida',
    name: 'Alvida',
    nameAr: 'ألفيدا',
    attack: 4, defense: 5,
    gender: 'female',
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: [],
    rarity: 'common', stars: 2,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'buggy',
    name: 'Buggy',
    nameAr: 'باغي',
    attack: 6, defense: 5,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'cabaji',
    name: 'Cabaji',
    nameAr: 'كاباجي',
    attack: 5, defense: 5,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'water',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'mr_3',
    name: 'Mr 3',
    nameAr: 'مستر 3',
    attack: 7, defense: 8,
    gender: 'male',
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'miss_doublefinger',
    name: 'Miss Doublefinger',
    nameAr: 'ميس دبل فينغر',
    attack: 8, defense: 7,
    gender: 'female',
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'mr_1',
    name: 'Mr 1',
    nameAr: 'مستر 1',
    attack: 10, defense: 11,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: [],
    rarity: 'rare', stars: 4,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'perona',
    name: 'Perona',
    nameAr: 'بيرونا',
    attack: 9, defense: 10,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'water',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'koby_hero',
    name: 'Koby Hero',
    nameAr: 'كوبي البطل',
    attack: 14, defense: 13,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'water',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'ichiji',
    name: 'Ichiji',
    nameAr: 'إيشيجي',
    attack: 15, defense: 14,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'One Piece',
    animationPreset: 'fire',
  },
  {
    id: 'niji',
    name: 'Niji',
    nameAr: 'نيجي',
    attack: 15, defense: 14,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'One Piece',
    animationPreset: 'lightning',
  },
  {
    id: 'yonji',
    name: 'Yonji',
    nameAr: 'يونجي',
    attack: 14, defense: 14,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'borsalino',
    name: 'Borsalino',
    nameAr: 'بورسالينو (كيزارو)',
    attack: 17, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    animationPreset: 'lightning',
  },
  {
    id: 'aokiji',
    name: 'Aokiji',
    nameAr: 'أوكيجي (كوزان)',
    attack: 17, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    animationPreset: 'default',
  },
  {
    id: 'akainu',
    name: 'Akainu',
    nameAr: 'أكاينو (سايكازوكو)',
    attack: 18, defense: 17,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'fire',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    animationPreset: 'fire',
  },
];
