import { Card } from './types';

// Batch 6/6 — Sword Art Online / Re:Zero / Overlord / Tower of God / Solo Leveling
export const CARDS_BATCH_6: Card[] = [
    {
        id: 'kirito',
        name: 'Kirito',
        nameAr: 'كيريتو',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'asuna',
        name: 'Asuna',
        nameAr: 'أسونا',
        attack: 14, defense: 13,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'lightning',
    },
    {
        id: 'sinon',
        name: 'Sinon',
        nameAr: 'سينون',
        attack: 13, defense: 12,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'epic', stars: 3,
        animationPreset: 'lightning',
    },
    {
        id: 'alice_zuberg',
        name: 'Alice Zuberg',
        nameAr: 'أليس زوبرغ',
        attack: 15, defense: 15,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'eugeo',
        name: 'Eugeo',
        nameAr: 'أوغيو',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'emilia',
        name: 'Emilia',
        nameAr: 'إيميليا',
        attack: 13, defense: 14,
        gender: 'female',
        race: 'elf', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'rem',
        name: 'Rem',
        nameAr: 'ريم',
        attack: 14, defense: 13,
        gender: 'female',
        race: 'orc', cardClass: 'swordsman', element: 'wind',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'wind',
    },
    {
        id: 'beatrice',
        name: 'Beatrice',
        nameAr: 'بياتريس',
        attack: 14, defense: 15,
        gender: 'female',
        race: 'human', cardClass: 'mage', element: 'earth',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'roswaal',
        name: 'Roswaal L Mathers',
        nameAr: 'روزوال ل ماذرز',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'subaru_natsuki',
        name: 'Subaru Natsuki',
        nameAr: 'سوبارو ناتسوكي',
        attack: 12, defense: 11,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'lightning',
    },
    {
        id: 'reinhard_van_astrea',
        name: 'Reinhard van Astrea',
        nameAr: 'راينهارد فان أستريا',
        attack: 19, defense: 18,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'ainz_ooal_gown',
        name: 'Ainz Ooal Gown',
        nameAr: 'أينز أوال غاون',
        attack: 18, defense: 17,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'albedo',
        name: 'Albedo',
        nameAr: 'ألبيدو',
        attack: 16, defense: 18,
        gender: 'female',
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'shalltear_bloodfallen',
        name: 'Shalltear Bloodfallen',
        nameAr: 'شالتير بلودفالن',
        attack: 17, defense: 16,
        gender: 'female',
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'cocytus',
        name: 'Cocytus',
        nameAr: 'كوكيتوس',
        attack: 16, defense: 17,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
    {
        id: 'demiurge',
        name: 'Demiurge',
        nameAr: 'ديميورج',
        attack: 17, defense: 16,
        race: 'undead', cardClass: 'mage', element: 'lightning',
        tags: ["magic"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'bam',
        name: 'Twenty-Fifth Bam',
        nameAr: 'بام الخامس والعشرون',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'rak_wraithraiser',
        name: 'Rak Wraithraiser',
        nameAr: 'راك ريذرايزر',
        attack: 16, defense: 15,
        race: 'orc', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'khun_aguero',
        name: 'Khun Aguero Agnes',
        nameAr: 'خون أغويرو أغنيس',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'mage', element: 'water',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'water',
    },
    {
        id: 'enryu',
        name: 'Enryu',
        nameAr: 'إنريو',
        attack: 19, defense: 18,
        race: 'human', cardClass: 'mage', element: 'lightning',
        tags: ["magic", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'jinwoo_sung',
        name: 'Sung Jinwoo',
        nameAr: 'سونغ جينوو',
        attack: 19, defense: 18,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'thomas_andre',
        name: 'Thomas Andre',
        nameAr: 'توماس أندريه',
        attack: 17, defense: 17,
        race: 'orc', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'goto_ryuji',
        name: 'Goto Ryuji',
        nameAr: 'غوتو ريوجي',
        attack: 16, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'liu_zhigang',
        name: 'Liu Zhigang',
        nameAr: 'ليو زيغانغ',
        attack: 16, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'ashborn',
        name: 'Ashborn (Shadow Monarch)',
        nameAr: 'أشبورن (ملك الظلال)',
        attack: 20, defense: 19,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'water',
    },
];
