import { Card } from './types';

// Batch 5/6 — 39 cards
export const CARDS_BATCH_5: Card[] = [
    {
        id: 'alvida',
        name: 'Alvida',
        nameAr: 'ألفيدا',
        attack: 4,
        defense: 5,
        race: 'human',
        cardClass: 'warrior',
        element: 'water',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'buggy',
        name: 'Buggy',
        nameAr: 'باغي',
        attack: 6,
        defense: 5,
        race: 'human',
        cardClass: 'warrior',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'cabaji',
        name: 'Cabaji',
        nameAr: 'كاباجي',
        attack: 5,
        defense: 5,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'common',
        stars: 1,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'mr_3',
        name: 'Mr 3',
        nameAr: 'مستر 3',
        attack: 7,
        defense: 8,
        race: 'human',
        cardClass: 'mage',
        element: 'earth',
        rarity: 'common',
        stars: 2,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'miss_doublefinger',
        name: 'Miss Doublefinger',
        nameAr: 'ميس دبل فينغر',
        attack: 8,
        defense: 7,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'common',
        stars: 1,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'mr_1',
        name: 'Mr 1',
        nameAr: 'مستر 1',
        attack: 10,
        defense: 11,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'perona',
        name: 'Perona',
        nameAr: 'بيرونا',
        attack: 9,
        defense: 10,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'ichiji',
        name: 'Ichiji',
        nameAr: 'إيشيجي',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'yonji',
        name: 'Yonji',
        nameAr: 'يونجي',
        attack: 14,
        defense: 14,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'common',
        stars: 2,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'borsalino',
        name: 'Borsalino',
        nameAr: 'كيزارو',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'mage',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'aokiji',
        name: 'Aokiji',
        nameAr: 'أوكيجي (كوزان)',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'akainu',
        name: 'Akainu',
        nameAr: 'أكاينو',
        attack: 18,
        defense: 17,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'One Piece',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'kaido',
        name: 'Kaido',
        nameAr: 'كايدو',
        attack: 20,
        defense: 19,
        race: 'demon',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'One Piece',
        specialAbility: 'قوة التنين — +2 هجوم و+4 دفاع هذه الجولة',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'big_mom',
        name: 'Big Mom',
        nameAr: 'بيغ مام',
        attack: 19,
        defense: 18,
        race: 'human',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'legendary',
        stars: 5,
        gender: 'female',
        universe: 'One Piece',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'uta',
        name: 'Uta',
        nameAr: 'أوتا',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'mage',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'One Piece',
        specialAbility: '',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'konohamaru',
        name: 'Konohamaru',
        nameAr: 'كونوهامارو',
        attack: 4,
        defense: 4,
        race: 'human',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'common',
        stars: 2,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'iruka',
        name: 'Iruka',
        nameAr: 'إيروكا',
        attack: 7,
        defense: 7,
        race: 'human',
        cardClass: 'fighter',
        element: 'water',
        rarity: 'common',
        stars: 2,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'asuma',
        name: 'Asuma',
        nameAr: 'أسوما',
        attack: 11,
        defense: 10,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'kurenai',
        name: 'Kurenai',
        nameAr: 'كوريناي',
        attack: 10,
        defense: 11,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Naruto',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'anko',
        name: 'Anko',
        nameAr: 'أنكو',
        attack: 11,
        defense: 10,
        race: 'human',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'danzo',
        name: 'Danzo',
        nameAr: 'دانزو',
        attack: 15,
        defense: 14,
        race: 'human',
        cardClass: 'fighter',
        element: 'wind',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'kabuto',
        name: 'Kabuto',
        nameAr: 'كابوتو',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'mage',
        element: 'water',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'mei_terumi',
        name: 'Mei Terumi',
        nameAr: 'مي تيرومي ',
        attack: 16,
        defense: 15,
        race: 'human',
        cardClass: 'mage',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Naruto',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'ay_raikage',
        name: 'Ay Raikage',
        nameAr: 'آي (رايكاجي)',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'warrior',
        element: 'lightning',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Naruto',
        animationPreset: 'lightning',
        tags: ['crown'],
    },
    {
        id: 'renji_abarai',
        name: 'Renji Abarai',
        nameAr: 'رينجي أباراي',
        attack: 14,
        defense: 13,
        race: 'human',
        cardClass: 'swordsman',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'byakuya_kuchiki',
        name: 'Byakuya Kuchiki',
        nameAr: 'بياكويا كوتشيكي',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'toshiro_hitsugaya',
        name: 'Toshiro Hitsugaya',
        nameAr: 'توشيرو هيتسوغايا',
        attack: 16,
        defense: 16,
        race: 'human',
        cardClass: 'swordsman',
        element: 'water',
        rarity: 'epic',
        stars: 4,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'kenpachi_zaraki',
        name: 'Kenpachi Zaraki',
        nameAr: 'كينباتشي زاراكي',
        attack: 19,
        defense: 15,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'fire',
        tags: ['crown'],
    },
    {
        id: 'kisuke_urahara',
        name: 'Kisuke Urahara',
        nameAr: 'كيسوكي أوراهارا',
        attack: 17,
        defense: 16,
        race: 'human',
        cardClass: 'swordsman',
        element: 'wind',
        rarity: 'legendary',
        stars: 5,
        gender: 'male',
        universe: 'Bleach',
        animationPreset: 'default',
        tags: ['crown'],
    },

    {
        id: 'leorio',
        name: 'Leorio',
        nameAr: 'ليوريو',
        attack: 10,
        defense: 10,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Hunter x Hunter',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'neferpitou',
        name: 'Neferpitou',
        nameAr: 'نيفيربيتو',
        attack: 18,
        defense: 17,
        race: 'demon',
        cardClass: 'warrior',
        element: 'wind',
        rarity: 'epic',
        stars: 4,
        gender: 'unknown',
        universe: 'Hunter x Hunter',
        animationPreset: 'default',
        tags: ['crown'],
    },
    {
        id: 'winry_rockbell',
        name: 'Winry Rockbell',
        nameAr: 'وينري روكبيل',
        attack: 4,
        defense: 5,
        race: 'human',
        cardClass: 'mage',
        element: 'earth',
        rarity: 'common',
        stars: 2,
        gender: 'female',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
    {
        id: 'riza_hawkeye',
        name: 'Riza Hawkeye',
        nameAr: 'ريزا هوكآي',
        attack: 13,
        defense: 12,
        race: 'human',
        cardClass: 'warrior',
        element: 'fire',
        rarity: 'rare',
        stars: 3,
        gender: 'female',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'fire',
        tags: [],
    },
    {
        id: 'alex_armstrong',
        name: 'Alex Armstrong',
        nameAr: 'أليكس أرمسترونغ',
        attack: 14,
        defense: 15,
        race: 'human',
        cardClass: 'warrior',
        element: 'earth',
        rarity: 'rare',
        stars: 3,
        gender: 'male',
        universe: 'Fullmetal Alchemist',
        animationPreset: 'default',
        tags: [],
    },
];
