import { Card } from './types';

// Batch 1/6 — 39 cards
export const CARDS_BATCH_1: Card[] = [
    {
        id: 'Turin',
        name: 'Turin',
        nameAr: 'تورين',
        attack: 12, defense: 10,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'sanji',
        name: 'Sanji',
        nameAr: 'سانجي',
        attack: 14, defense: 12,
        gender: 'male',
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'nami',
        name: 'Nami',
        nameAr: 'نامي',
        attack: 6, defense: 8,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'lightning',
    },
    {
        id: 'usopp',
        name: 'Usopp',
        nameAr: 'أوسوب',
        attack: 8, defense: 7,
        race: 'human', cardClass: 'archer', element: 'wind',
        tags: ["bow"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'chopper',
        name: 'Chopper',
        nameAr: 'تشوبر',
        attack: 5, defense: 6,
        race: 'orc', cardClass: 'healer', element: 'water',
        tags: ["magic"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'robin',
        name: 'Robin',
        nameAr: 'روبين',
        attack: 11, defense: 9,
        gender: 'female',
        race: 'human', cardClass: 'mage', element: 'earth',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'franky',
        name: 'Franky',
        nameAr: 'فرانكي',
        attack: 10, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'brook',
        name: 'Brook',
        nameAr: 'بروك',
        attack: 11, defense: 8,
        race: 'undead', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'jinbe',
        name: 'Jinbe',
        nameAr: 'جينبي',
        attack: 15, defense: 14,
        race: 'orc', cardClass: 'swordsman', element: 'water',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'boa_hancock',
        name: 'Boa Hancock',
        nameAr: 'بوا هانكوك',
        attack: 15, defense: 12,
        gender: 'female',
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'marco',
        name: 'Marco',
        nameAr: 'ماركو',
        attack: 16, defense: 15,
        race: 'orc', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'ace',
        name: 'Ace',
        nameAr: 'إيس',
        attack: 16, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'law',
        name: 'Law',
        nameAr: 'لاو',
        attack: 16, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'water',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'katakuri',
        name: 'Katakuri',
        nameAr: 'كاتاكوري',
        attack: 17, defense: 16,
        race: 'orc', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'whitebeard',
        name: 'Whitebeard',
        nameAr: 'وايتبيرد',
        attack: 18, defense: 17,
        race: 'orc', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'shanks',
        name: 'Shanks',
        nameAr: 'شانكس',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'dracule_mihawk',
        name: 'Dracule Mihawk',
        nameAr: 'دراكول ميهوك',
        attack: 19, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'roronoa_zoro',
        name: 'Roronoa Zoro',
        nameAr: 'رورونوا زورو',
        attack: 18, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'monkey_d_luffy',
        name: 'Monkey D. Luffy',
        nameAr: 'مونكي دي لوفي',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'sakura_haruno',
        name: 'Sakura Haruno',
        nameAr: 'ساكورا هارونو',
        attack: 3, defense: 4,
        gender: 'female',
        race: 'human', cardClass: 'healer', element: 'earth',
        tags: ["magic"],
        rarity: 'common', stars: 1,
        animationPreset: 'default',
    },
    {
        id: 'rock_lee',
        name: 'Rock Lee',
        nameAr: 'روك لي',
        attack: 8, defense: 7,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'rare', stars: 3,
        animationPreset: 'default',
    },
    {
        id: 'gaara',
        name: 'Gaara',
        nameAr: 'غارا',
        attack: 13, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'tsunade',
        name: 'Tsunade',
        nameAr: 'تسونادي',
        attack: 13, defense: 14,
        gender: 'female',
        race: 'human', cardClass: 'healer', element: 'earth',
        tags: ["magic"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
    {
        id: 'jiraiya',
        name: 'Jiraiya',
        nameAr: 'جيرايا',
        attack: 15, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'fire',
    },
    {
        id: 'orochimaru',
        name: 'Orochimaru',
        nameAr: 'أوروتشيمارو',
        attack: 14, defense: 14,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
        cardEffects: ['poison'],
    },
    {
        id: 'sasuke_uchiha',
        name: 'Sasuke Uchiha',
        nameAr: 'ساسكي أوتشيها',
        attack: 17, defense: 15,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'itachi_uchiha',
        name: 'Itachi Uchiha',
        nameAr: 'إيتاتشي أوتشيها',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'madara_uchiha',
        name: 'Madara Uchiha',
        nameAr: 'مادارا أوتشيها',
        attack: 18, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'hashirama_senju',
        name: 'Hashirama Senju',
        nameAr: 'هاشيراما سينجو',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'minato_namikaze',
        name: 'Minato Namikaze',
        nameAr: 'ميناتو ناميكازي',
        attack: 18, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'lightning',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'lightning',
    },
    {
        id: 'nagato',
        name: 'Nagato',
        nameAr: 'ناغاتو',
        attack: 17, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'fire',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'fire',
    },
    {
        id: 'naruto_uzumaki',
        name: 'Naruto Uzumaki',
        nameAr: 'ناروتو أوزوماكي',
        attack: 18, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'villager_a',
        name: 'Villager A',
        nameAr: 'مواطن عادي',
        attack: 1, defense: 1,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'default',
    },
    {
        id: 'villager_b',
        name: 'Villager B',
        nameAr: 'مواطن ب',
        attack: 1, defense: 1,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'default',
    },
    {
        id: 'villager_c',
        name: 'Villager C',
        nameAr: 'مواطن ج',
        attack: 1, defense: 1,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'default',
    },
    {
        id: 'mob',
        name: 'Mob',
        nameAr: 'موب',
        attack: 1, defense: 1,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'common', stars: 1,
        animationPreset: 'default',
    },
    {
        id: 'guts',
        name: 'Guts',
        nameAr: 'غاتس',
        attack: 18, defense: 16,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'griffith',
        name: 'Griffith',
        nameAr: 'غريفيث',
        attack: 17, defense: 17,
        race: 'human', cardClass: 'swordsman', element: 'wind',
        tags: ["sword", "crown"],
        rarity: 'legendary', stars: 5,
        animationPreset: 'default',
    },
    {
        id: 'elden_ring_knight',
        name: 'Elden Ring Knight',
        nameAr: 'فارس إلدن رينغ',
        attack: 10, defense: 13,
        race: 'human', cardClass: 'swordsman', element: 'earth',
        tags: ["sword"],
        rarity: 'epic', stars: 4,
        animationPreset: 'default',
    },
];
