import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 4/6 — Cards 139 to 184
// Universes: MHA, OPM, Bloodborne, LotM, Blue Exorcist, Chainsaw Man, Re:Zero
// Changes: the_hunter legendary→epic (Excel v4)

export const CARDS_BATCH_4: Card[] = [
  {
    id: 'shoto_todoroki',
    nameAr: 'شوتو تودوروكي',
    universe: 'My Hero Academia',
    attack: 12, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'endeavor',
    nameAr: 'إنديفر',
    universe: 'My Hero Academia',
    attack: 14, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'katsuki_bakugo',
    nameAr: 'كاتسوكي باكوغو',
    universe: 'My Hero Academia',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'izuku_midoriya',
    nameAr: 'إيزوكو ميدوريا',
    universe: 'My Hero Academia',
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'tomura_shigaraki',
    nameAr: 'توموروا شيغاراكي',
    universe: 'My Hero Academia',
    attack: 14, defense: 15,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'all_might',
    nameAr: 'أول مايت',
    universe: 'My Hero Academia',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'king',
    nameAr: 'كينغ',
    universe: 'One Punch Man',
    attack: 1, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 1,
    animationPreset: 'lightning',
  },
  {
    id: 'genos',
    nameAr: 'جينوس',
    universe: 'One Punch Man',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'garou',
    nameAr: 'غارو',
    universe: 'One Punch Man',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'saitama',
    nameAr: 'سايتاما',
    universe: 'One Punch Man',
    attack: 17, defense: 17,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'lightning',
  },
  {
    id: 'the_plain_doll',
    nameAr: 'الدمية',
    universe: 'Bloodborne',
    attack: 3, defense: 0,
    race: 'human', cardClass: 'mage', element: 'water',
    tags: ["magic"],
    rarity: 'common', stars: 1,
    animationPreset: 'default',
  },
  {
    id: 'suspicious_beggar',
    nameAr: 'المتسول المشبوه',
    universe: 'Bloodborne',
    attack: 9, defense: 7,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'eileen_the_crow',
    nameAr: 'إيلين الغراب',
    universe: 'Bloodborne',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'father_gascoigne',
    nameAr: 'الأب غاسكوين',
    universe: 'Bloodborne',
    attack: 14, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'the_hunter',
    nameAr: 'الصياد',
    universe: 'Bloodborne',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'archer', element: 'ice',
    tags: ["bow", "crown"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
    cardEffects: ['charge'],
  },
  {
    id: 'lady_maria',
    nameAr: 'الليدي ماريا',
    universe: 'Bloodborne',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'laurence',
    nameAr: 'لورانس',
    universe: 'Bloodborne',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'gehrman',
    nameAr: 'جيرمان',
    universe: 'Bloodborne',
    attack: 18, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ludwig',
    nameAr: 'لودفيغ',
    universe: 'Bloodborne',
    attack: 17, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'emlyn_white',
    nameAr: 'إيميلين وايت',
    universe: 'Lord of the Mysteries',
    attack: 8, defense: 7,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'alger_wilson',
    nameAr: 'ألغر ويلسون',
    universe: 'Lord of the Mysteries',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'klein_moretti',
    nameAr: 'كلاين موريتي',
    universe: 'Lord of the Mysteries',
    attack: 17, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'feanor',
    nameAr: 'فيانور',
    universe: 'Lord of the Mysteries',
    attack: 17, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'rin_okumura',
    nameAr: 'رين أوكومورا',
    universe: 'Blue Exorcist',
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'amaimon',
    nameAr: 'عمايمون',
    universe: 'Blue Exorcist',
    attack: 13, defense: 14,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'power',
    nameAr: 'باور',
    universe: 'Chainsaw Man',
    attack: 12, defense: 12,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'denji',
    nameAr: 'دينجي',
    universe: 'Chainsaw Man',
    attack: 15, defense: 11,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'makima',
    nameAr: 'ماكيما',
    universe: 'Chainsaw Man',
    attack: 17, defense: 16,
    race: 'demon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
    cardEffects: ['poison'],
  },
  {
    id: 'subaru_natsuki',
    nameAr: 'سوبارو ناتسوكي',
    universe: 'Re:Zero',
    attack: 6, defense: 5,
    race: 'human', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
];
