import type { Card } from '../lib/game/types';

// Batch 3/6 — One Piece (legends end) + Naruto + Bleach (start)
export const CARDS_BATCH_3: Card[] = [
  {
    id: 'kaido',
    name: 'Kaido',
    nameAr: 'كايدو',
    attack: 20, defense: 19,
    gender: 'male',
    race: 'demon', cardClass: 'warrior', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    specialAbility: 'لا يمكن هزيمته بضربة واحدة',
    animationPreset: 'lightning',
  },
  {
    id: 'big_mom',
    name: 'Big Mom',
    nameAr: 'بيغ مام',
    attack: 19, defense: 18,
    gender: 'female',
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    animationPreset: 'lightning',
  },
  {
    id: 'uta',
    name: 'Uta',
    nameAr: 'أوتا',
    attack: 16, defense: 15,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'One Piece',
    specialAbility: 'تحبس الأعداء في عالم الأغاني',
    animationPreset: 'default',
  },
  {
    id: 'konohamaru',
    name: 'Konohamaru',
    nameAr: 'كونوهامارو',
    attack: 4, defense: 4,
    gender: 'male',
    race: 'human', cardClass: 'fighter', element: 'wind',
    tags: [],
    rarity: 'common', stars: 2,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'iruka',
    name: 'Iruka',
    nameAr: 'إيروكا',
    attack: 7, defense: 7,
    gender: 'male',
    race: 'human', cardClass: 'fighter', element: 'water',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'asuma',
    name: 'Asuma',
    nameAr: 'أسوما',
    attack: 11, defense: 10,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'wind',
    tags: [],
    rarity: 'rare', stars: 4,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'kurenai',
    name: 'Kurenai',
    nameAr: 'كوريناي',
    attack: 10, defense: 11,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'fire',
    tags: [],
    rarity: 'rare', stars: 3,
    universe: 'Naruto',
    animationPreset: 'fire',
  },
  {
    id: 'anko',
    name: 'Anko',
    nameAr: 'أنكو',
    attack: 11, defense: 10,
    gender: 'female',
    race: 'human', cardClass: 'fighter', element: 'wind',
    tags: [],
    rarity: 'rare', stars: 4,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'danzo',
    name: 'Danzo',
    nameAr: 'دانزو',
    attack: 15, defense: 14,
    gender: 'male',
    race: 'human', cardClass: 'fighter', element: 'wind',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'kabuto',
    name: 'Kabuto',
    nameAr: 'كابوتو',
    attack: 14, defense: 13,
    gender: 'male',
    race: 'human', cardClass: 'mage', element: 'water',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'mei_terumi',
    name: 'Mei Terumi',
    nameAr: 'ميي تيروميه',
    attack: 16, defense: 15,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'fire',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Naruto',
    animationPreset: 'fire',
  },
  {
    id: 'ay_raikage',
    name: 'Ay Raikage',
    nameAr: 'آي (رايكاجي)',
    attack: 17, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Naruto',
    animationPreset: 'lightning',
  },
  {
    id: 'konan',
    name: 'Konan',
    nameAr: 'كونان',
    attack: 16, defense: 15,
    gender: 'female',
    race: 'human', cardClass: 'mage', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Naruto',
    animationPreset: 'default',
  },
  {
    id: 'renji_abarai',
    name: 'Renji Abarai',
    nameAr: 'رينجي أباراي',
    attack: 14, defense: 13,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'fire',
    tags: [],
    rarity: 'epic', stars: 4,
    universe: 'Bleach',
    animationPreset: 'fire',
  },
  {
    id: 'ichigo_bankai',
    name: 'Ichigo Bankai',
    nameAr: 'إيتشيغو (بانكاي)',
    attack: 19, defense: 17,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'fire',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    specialAbility: 'تحرير الروح الكاملة',
    animationPreset: 'fire',
  },
  {
    id: 'byakuya_kuchiki',
    name: 'Byakuya Kuchiki',
    nameAr: 'بياكويا كوتشيكي',
    attack: 17, defense: 16,
    gender: 'male',
    race: 'human', cardClass: 'swordsman', element: 'wind',
    tags: ["crown"],
    rarity: 'legendary', stars: 5,
    universe: 'Bleach',
    animationPreset: 'default',
  },
];
