import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 5/6 — Cards 185 to 230
// Universes: Re:Zero, The Legend of Zelda, Sword Art Online, Log Horizon, The Elder Scrolls, Fairy Tail, Monster Hunter, Castlevania
// No changes from Excel v4 — all values match

export const CARDS_BATCH_5: Card[] = [
  {
    id: 'satella',
    nameAr: 'ساتيلا',
    universe: 'Re:Zero',
    attack: 19, defense: 16,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'ganondorf',
    nameAr: 'غانوندورف',
    universe: 'The Legend of Zelda',
    attack: 16, defense: 17,
    race: 'elf', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
  },
  {
    id: 'silica',
    nameAr: 'سيليكا',
    universe: 'Sword Art Online',
    attack: 9, defense: 9,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'eugeo',
    nameAr: 'يوجيو',
    universe: 'Sword Art Online',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'heathcliff_kayaba',
    nameAr: 'هيثكليف (كايابا)',
    universe: 'Sword Art Online',
    attack: 13, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alice_zuberg',
    nameAr: 'أليس زيوبيرغ',
    universe: 'Sword Art Online',
    attack: 13, defense: 13,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rundelhaus',
    nameAr: 'روندلهاوس',
    universe: 'Log Horizon',
    attack: 8, defense: 8,
    race: 'elf', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'nyanta',
    nameAr: 'نيانتا',
    universe: 'Log Horizon',
    attack: 11, defense: 12,
    race: 'elf', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'paarthurnax',
    nameAr: 'بارثورناكس',
    universe: 'The Elder Scrolls',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'alduin',
    nameAr: 'ألدوين',
    universe: 'The Elder Scrolls',
    attack: 17, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'happy',
    nameAr: 'هابي',
    universe: 'Fairy Tail',
    attack: 4, defense: 2,
    race: 'orc', cardClass: 'warrior', element: 'fire',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'fire',
  },
  {
    id: 'igneel',
    nameAr: 'إيغنيل',
    universe: 'Fairy Tail',
    attack: 16, defense: 17,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'acnologia',
    nameAr: 'أكنولوجيا',
    universe: 'Fairy Tail',
    attack: 16, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'fatalis',
    nameAr: 'فاتاليس',
    universe: 'Monster Hunter',
    attack: 18, defense: 16,
    race: 'dragon', cardClass: 'warrior', element: 'fire',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'fire',
  },
  {
    id: 'hector',
    nameAr: 'هيكتور',
    universe: 'Castlevania',
    attack: 14, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'isaac',
    nameAr: 'إسحاق',
    universe: 'Castlevania',
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'alucard',
    nameAr: 'ألوكارد',
    universe: 'Castlevania',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'death',
    nameAr: 'الموت',
    universe: 'Castlevania',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'dracula',
    nameAr: 'دراكولا',
    universe: 'Castlevania',
    attack: 18, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
];
