import { Card, Element, ElementAdvantage, Effect, ELEMENT_ADVANTAGES, ELEMENT_WEAKNESSES, ELEMENT_MULTIPLIER } from './types';

// Batch 6/6 — Cards 231 to 275
// Universes: Dark Souls, Overlord, The Witcher, Vinland Saga, JJK, Gurren Lagann, NGE, Mega Man, Berserk, Claymore, HxH, AoT, MHA
// No changes from Excel v4 — all values match

export const CARDS_BATCH_6: Card[] = [
  {
    id: 'smough',
    nameAr: 'سموغ',
    universe: 'Dark Souls',
    attack: 15, defense: 11,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'ornstein',
    nameAr: 'أورنشتاين',
    universe: 'Dark Souls',
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'gwyn',
    nameAr: 'غوين',
    universe: 'Dark Souls',
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'artorias',
    nameAr: 'أرتورياس',
    universe: 'Dark Souls',
    attack: 16, defense: 17,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'lich_general',
    nameAr: 'آينز أوال غاون',
    universe: 'Overlord',
    attack: 15, defense: 13,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'pandoras_actor',
    nameAr: 'ممثل باندورا',
    universe: 'Overlord',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'ice',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'shalltear',
    nameAr: 'شالتير',
    universe: 'Overlord',
    attack: 14, defense: 15,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'regis',
    nameAr: 'ريجيس',
    universe: 'The Witcher',
    attack: 15, defense: 12,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'ice',
  },
  {
    id: 'gaunter_o_dimm',
    nameAr: 'غونتر أو ديم',
    universe: 'The Witcher',
    attack: 17, defense: 16,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'ice',
    cardEffects: ['taunt'],
  },
  {
    id: 'floki',
    nameAr: 'فلوكي',
    universe: 'Vinland Saga',
    attack: 9, defense: 8,
    race: 'undead', cardClass: 'warrior', element: 'ice',
    tags: ["sword"],
    rarity: 'rare', stars: 3,
    animationPreset: 'ice',
  },
  {
    id: 'askeladd',
    nameAr: 'أسكيلاد',
    universe: 'Vinland Saga',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorfinn',
    nameAr: 'ثورفين',
    universe: 'Vinland Saga',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'thorkell',
    nameAr: 'ثوركيل',
    universe: 'Vinland Saga',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'yuta_okkotsu',
    nameAr: 'يوتا أوكوتسو',
    universe: 'Jujutsu Kaisen',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'kamina',
    nameAr: 'كامينا',
    universe: 'Gurren Lagann',
    attack: 12, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'lordgenome',
    nameAr: 'لورد غينوم',
    universe: 'Gurren Lagann',
    attack: 14, defense: 13,
    race: 'human', cardClass: 'knight', element: 'lightning',
    tags: ["sword", "shield"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
    cardEffects: ['divine_shield'],
  },
  {
    id: 'asuka_langley',
    nameAr: 'أسوكا لانغلي',
    universe: 'Neon Genesis Evangelion',
    attack: 13, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'rei_ayanami',
    nameAr: 'ري أيانامي',
    universe: 'Neon Genesis Evangelion',
    attack: 13, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'kaworu_nagisa',
    nameAr: 'كاورو ناغيسا',
    universe: 'Neon Genesis Evangelion',
    attack: 14, defense: 13,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'dr_cossack',
    nameAr: 'د. كوساك',
    universe: 'Mega Man',
    attack: 6, defense: 6,
    race: 'human', cardClass: 'mage', element: 'earth',
    tags: ["magic"],
    rarity: 'rare', stars: 3,
    animationPreset: 'default',
  },
  {
    id: 'mega_man',
    nameAr: 'ميغا مان',
    universe: 'Mega Man',
    attack: 13, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'bass',
    nameAr: 'باس',
    universe: 'Mega Man',
    attack: 15, defense: 11,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zero',
    nameAr: 'زيرو',
    universe: 'Mega Man',
    attack: 15, defense: 12,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'sigma',
    nameAr: 'سيغما',
    universe: 'Mega Man',
    attack: 14, defense: 14,
    race: 'human', cardClass: 'mage', element: 'lightning',
    tags: ["magic"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'zodd',
    nameAr: 'زود',
    universe: 'Berserk',
    attack: 15, defense: 12,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'guts',
    nameAr: 'غاتس',
    universe: 'Berserk',
    attack: 16, defense: 16,
    race: 'human', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'griffith',
    nameAr: 'غريفث',
    universe: 'Berserk',
    attack: 16, defense: 16,
    race: 'orc', cardClass: 'warrior', element: 'earth',
    tags: ["sword", "crown"],
    rarity: 'legendary', stars: 5,
    animationPreset: 'default',
  },
  {
    id: 'clare',
    nameAr: 'كلير',
    universe: 'Claymore',
    attack: 13, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'lightning',
  },
  {
    id: 'neferpitou',
    nameAr: 'نيفيربيتو',
    universe: 'Hunter x Hunter',
    attack: 15, defense: 11,
    race: 'orc', cardClass: 'warrior', element: 'wind',
    tags: ["sword"],
    rarity: 'epic', stars: 4,
    animationPreset: 'default',
  },
  {
    id: 'mineta',
    nameAr: 'مينيتا',
    universe: 'My Hero Academia',
    attack: 3, defense: 2,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'common', stars: 2,
    animationPreset: 'lightning',
  },
  {
    id: 'Turin_Turambar',
    nameAr: 'تورين تورامبار',
    universe: 'Special',
    attack: 0, defense: 0,
    race: 'human', cardClass: 'warrior', element: 'lightning',
    tags: ["sword"],
    rarity: 'special', stars: 4,
    animationPreset: 'lightning',
  },
];
